import { chromium } from 'playwright';
const B = 'http://localhost:5178/';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1360, height: 820 } });
const rows = async () => (await page.$$eval('[data-testid^="job-row-"]', (els) => els.map((e) => e.textContent.replace(/\s+/g, ' ').trim().slice(0, 40)))).join('\n');
await page.goto(B + '?platform=windows&view=jobs');
await page.waitForTimeout(700);
await page.click('[data-testid="excluded-divider"]');
await page.waitForTimeout(400);
await page.click('[data-testid="job-row-freelance-900412"]');
await page.waitForTimeout(800);
await page.click('[data-testid="reader-include"]');
await page.waitForTimeout(4000);
console.log('AFTER 4s\n' + await rows());
const calls = await page.evaluate(() => window.__harness.calls.filter(c => c[0]==="list_jobs").slice(-4)); const all = await page.evaluate(() => window.__harness.calls.slice(-12).map(c=>c[0])); console.log(all.join(" "));
console.log(JSON.stringify(calls));
const q = calls.find(c=>c[1].query.limit>0)[1].query;
const l = await page.evaluate((q) => window.__harness.list(q).jobs.map(j => j.title + ' ' + (j.match?.score) + ' ' + j.match?.status), q);
console.log('STUB\n' + l.join('\n'));
await browser.close();
