// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FetchRange } from "./FetchRange";
import type { JobCounts } from "./JobCounts";
import type { Language } from "./Language";
import type { Mailbox } from "./Mailbox";
import type { Palette } from "./Palette";
import type { Platform } from "./Platform";
import type { PortalState } from "./PortalState";
import type { ProfileEntry } from "./ProfileEntry";
import type { ProfileInfo } from "./ProfileInfo";
import type { ResetSummary } from "./ResetSummary";
import type { RunSnapshot } from "./RunSnapshot";
import type { RunSummary } from "./RunSummary";
import type { SettingsView } from "./SettingsView";

/**
 * Everything the interface needs at the start (and after a reload).
 */
export type AppState = { platform: Platform, 
/**
 * The app's version (`3.0.0`), shown in Einstellungen under Wartung.
 */
version: string, dryRun: boolean, 
/**
 * The demo (`--demo`): a data folder of its own made from bundled ads; it never
 * fetches (`Demo` refuses the mailbox, the portals and the vault).
 */
demo: boolean, 
/**
 * No run has finished yet and no job is known.
 */
firstRun: boolean, 
/**
 * A fetch has completed its mailbox step (`pipeline::has_completed_fetch`): the
 * first-run page stays until then, also after a first fetch that failed.
 */
setupDone: boolean, 
/**
 * The run in progress (after a reload the interface picks up from here).
 */
running: RunSnapshot | null, settings: SettingsView, mailbox: Mailbox, 
/**
 * The active profile.
 */
profile: ProfileInfo | null, 
/**
 * Every profile of the work folder, the active one marked (empty without one).
 */
profiles: Array<ProfileEntry>, portals: Array<PortalState>, 
/**
 * Which alert mails "Postfach abrufen" reads.
 */
fetchRange: FetchRange, 
/**
 * The Excel file is written with every export.
 */
exportExcel: boolean, 
/**
 * The CSV file is written with every export.
 */
exportCsv: boolean, 
/**
 * The language of the interface and the exports: the chosen one, else the OS language.
 */
language: Language, 
/**
 * The colours of the page and the window (Excel and the icon keep Light).
 */
palette: Palette, 
/**
 * The last fetch - a rescore or a details run is none.
 */
lastRun: RunSummary | null, counts: JobCounts, matchPending: number, dataDir: string, logDir: string, resetReport: ResetSummary | null, };
