// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A term the ads ask for that the profile does not cover, and in how many jobs
 * ("Häufig verlangt" in the Profil).
 */
export type AskedTerm = { 
/**
 * The ad's words (of the newest job that asks for it).
 */
term: string, count: number, };
