// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TermField } from "./TermField";

/**
 * A term the ads ask for that the profile does not cover, the field of the profile it
 * belongs to, and in how many jobs ("Häufig verlangt" in the Profil).
 */
export type AskedTerm = { 
/**
 * The term in the ad's words, without what only says that or how much it is wanted
 * ("Anaplan" of "Kenntnisse in Anaplan"; of the newest job that asks for it).
 */
term: string, field: TermField, count: number, };
