// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupKind } from "./BackupKind";

/**
 * A copy of the database the user can go back to.
 */
export type Backup = { 
/**
 * Its file name in `backups/`, the only name a restore takes.
 */
id: string, kind: BackupKind, 
/**
 * When it was written.
 */
at: string, bytes: number, };
