// Generated by core/src/view/ts.rs from core/src/model.rs (cargo test -p jobalert-core ipc_types). Do not edit.
import type { Band } from "./Band";

/** Minimum score of the high band. */
export const HIGH_FROM = 80;
/** Minimum score of the mid band. */
export const MID_FROM = 40;
/** The lowest score of each band. */
export const BAND_FROM: Record<Band, number> = { high: 80, mid: 40, low: 0 };

/** The band of a score (`model::band`). */
export function bandOf(score: number): Band {
  return score >= HIGH_FROM ? "high" : score >= MID_FROM ? "mid" : "low";
}
