// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which alert mails "Postfach abrufen" reads (`mail::scan::Scope`): since the last fetch
 * that covered the time before it, the last 7 or 30 days, or every alert mail. The scan
 * state per portal advances only when the range covered the gap since it.
 */
export type FetchRange = "sinceLast" | "days7" | "days30" | "all";
