// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts of the list (with the search and the filter applied, whatever the place), from the
 * same statement as the page. Every number of the list comes from here: the rows each place
 * holds (the length of the list, the other places' search hits, "Papierkorb leeren") and
 * its section "Ausgeschlossen".
 */
export type JobCounts = { 
/**
 * In the inbox ("Eingang").
 */
inbox: number, archive: number, 
/**
 * In the trash ("Papierkorb").
 */
trash: number, 
/**
 * Excluded, in the inbox.
 */
excluded: number, 
/**
 * Excluded, in the archive (the section "Ausgeschlossen" of the Archiv tab).
 */
excludedArchive: number, 
/**
 * Excluded, in the trash (the section "Ausgeschlossen" of the Papierkorb tab).
 */
excludedTrash: number, };
