// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobMail } from "./JobMail";
import type { JobView } from "./JobView";
import type { MatchDetail } from "./MatchDetail";
import type { TextLayout } from "./TextLayout";

/**
 * One job in the reader.
 */
export type JobDetail = { job: JobView, 
/**
 * The full text (only with details `ok`).
 */
text: string | null, url: string, fetchedAt: string | null, mail: JobMail, 
/**
 * Headings and list lines of the text (empty without one).
 */
layout: TextLayout, match: MatchDetail | null, };
