// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Band } from "./Band";
import type { JobSort } from "./JobSort";
import type { Place } from "./Place";
import type { Portal } from "./Portal";

/**
 * Which jobs the list shows: the jobs of one place, optionally only the unread ones.
 */
export type JobQuery = { place: Place, 
/**
 * Only the unread jobs (the excluded ones last, uncounted).
 */
unread: boolean, 
/**
 * By match, or by date: the alert mail's, in the trash the day the job went there.
 */
sort: JobSort, search: string | null, 
/**
 * The filter (funnel menu): only this portal's jobs; `null` = every portal. Like the
 * search it narrows the list and all its counts.
 */
portal: Portal | null, 
/**
 * The filter: only jobs scored in this band or better (`mid` = mid and high, `high` =
 * high only); unscored and excluded jobs pass only with `null`.
 */
minBand: Band | null, 
/**
 * At most [`MAX_PAGE`]; 0 = counts only.
 */
limit: number, offset: number, };
