// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Band } from "./Band";
import type { JobSort } from "./JobSort";
import type { Place } from "./Place";
import type { Portal } from "./Portal";

/**
 * Which jobs the list shows: the jobs of one place, narrowed by the search and the filter.
 */
export type JobQuery = { place: Place, 
/**
 * By match, or by date: the alert mail's, in the trash the day the job went there.
 */
sort: JobSort, search: string | null, 
/**
 * The filter (funnel menu): only these portals' jobs; empty = every portal. Like the
 * search it narrows the list and all its counts.
 */
portals: Array<Portal>, 
/**
 * The filter: only jobs scored in these bands (`high`, `mid`, `low`); unscored and
 * excluded jobs pass only while it is empty.
 */
bands: Array<Band>, 
/**
 * The filter "Aus dem letzten Abruf" (the "Zeigen" of a fetch's toast): only the new
 * jobs this run brought, the ones its toast counts (`RunSummary.newJobs`: first seen in
 * it, not excluded). `null` = every job.
 */
run: number | null, 
/**
 * The filter "Gefunden": only jobs that came at or after this moment (Unix seconds;
 * the alert mail's date, else when the app first saw the job, as "Nach Datum" orders
 * them). The page names the start of today, of the last 7 or of the last 30 days in
 * the user's time zone. `null` = every job.
 */
receivedSince: number | null, 
/**
 * At most [`MAX_PAGE`]; 0 = counts only.
 */
limit: number, offset: number, };
