// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The key facts of an ad as the engine read them (the page facts first, then the text):
 * numbers and codes for the list row and the reader, `null` when the ad says nothing.
 */
export type KeyFacts = { 
/**
 * Highest rate amount stated, per day or per hour (`hourly`).
 */
rate: number | null, hourly: boolean | null, 
/**
 * Currency code of a rate not in EUR (`CHF`).
 */
currency: string | null, 
/**
 * The ad names a rate to be agreed (`nach Absprache`) without an amount.
 */
rateOpen: boolean | null, 
/**
 * Start: `now`, `vague` or an ISO date (`2026-11-01`).
 */
start: string | null, 
/**
 * Duration in months.
 */
months: number | null, 
/**
 * Remote share in percent, from and to (equal when the ad states one share).
 */
remoteFrom: number | null, remoteTo: number | null, 
/**
 * Contract type: `interim` (management), `freelance` (a project), `permanent` or `anue`
 * (`null` when unclear).
 */
contract: string | null, 
/**
 * Workload in percent of a five-day week, from and to (full-time 100, `3 Tage/Woche`
 * 60, `20 h/Woche` 50; part-time without a number has no `from` and `to` 80); left out
 * when the ad says nothing.
 */
workloadFrom?: number, workloadTo?: number, 
/**
 * Annual salary in euros an employment states (a monthly one times twelve); left out when
 * the ad names none or names it in another currency.
 */
salary?: number, 
/**
 * The salary is a lower bound only (`ab 100.000 €`); left out without a salary.
 */
salaryLowerBound?: boolean, };
