// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The key facts of an ad as the engine read them (the page facts first, then the text):
 * numbers and codes for the list row and the reader, `null` when the ad says nothing.
 */
export type KeyFacts = { 
/**
 * Highest rate amount stated, per day or per hour (`hourly`).
 */
rate: number | null, hourly: boolean | null, 
/**
 * Currency code of a rate not in EUR (`CHF`).
 */
currency: string | null, 
/**
 * The ad names a rate to be agreed (`nach Absprache`) without an amount.
 */
rateOpen: boolean | null, 
/**
 * Start: `now`, `vague` or an ISO date (`2026-11-01`).
 */
start: string | null, 
/**
 * Duration in months (`weeks` instead when the ad states weeks).
 */
months: number | null, 
/**
 * Duration in weeks, as the ad states it (never rounded up to months); left out when the
 * ad states months or nothing.
 */
weeks?: number, 
/**
 * The lower end of a range of durations, in the unit of `months` or `weeks` (`3 bis 6
 * Monate`); left out without a range.
 */
durationFrom?: number, 
/**
 * The lower end of a range of rates, per day or per hour as `rate` (`900 bis 1.200
 * €/Tag`); left out without a range.
 */
rateFrom?: number, 
/**
 * Remote share in percent, from and to (equal when the ad states one share).
 */
remoteFrom: number | null, remoteTo: number | null, 
/**
 * Contract type: `interim` (management), `freelance` (a project), `permanent` or `anue`
 * (`null` when unclear).
 */
contract: string | null, 
/**
 * Workload in percent of a five-day week, from and to (full-time 100, `3 Tage/Woche`
 * 60, `20 h/Woche` 50; part-time without a number has no `from` and `to` 80); left out
 * when the ad says nothing.
 */
workloadFrom?: number, workloadTo?: number, 
/**
 * Annual salary in euros an employment states (a monthly one times twelve); left out when
 * the ad names none or names it in another currency.
 */
salary?: number, 
/**
 * The salary is a lower bound only (`ab 100.000 €`); left out without a salary.
 */
salaryLowerBound?: boolean, 
/**
 * The lower end of a range of salaries in euros per year; left out without a range.
 */
salaryFrom?: number, 
/**
 * The bonus share (percent) the salary's sentence names (`plus bis zu 20 % Bonus`): the
 * minimum salary is compared with the salary and its bonus; left out without one.
 */
salaryBonus?: number, 
/**
 * The application deadline the ad names, an ISO date (`2026-10-15`); left out without
 * one.
 */
deadline?: string, 
/**
 * The contact the ad names: a person, an e-mail address and a phone number, each as the
 * ad writes it; each left out when the ad names none.
 */
contactName?: string, contactEmail?: string, contactPhone?: string, };
