// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The app's language: German unless the user chose English in Einstellungen
 * ([`Language::DEFAULT`]); only the macOS menu follows the OS ([`Language::from_locale`]).
 */
export type Language = "de" | "en";
