// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorInfo } from "./ErrorInfo";
import type { MailboxCheck } from "./MailboxCheck";
import type { VaultKind } from "./VaultKind";

export type Mailbox = { 
/**
 * The stored Gmail address; `null` = no mailbox connected.
 */
user: string | null, vault: VaultKind, 
/**
 * The vault could not be read.
 */
error: ErrorInfo | null, 
/**
 * What "Verbinden" found in the mailbox in this session (the sign-in worked). `null`
 * before a "Verbinden", and when it signed in but could not count (too slow, or Gmail
 * failed on a mail): the answer to `save_mailbox` is then signed in and not counted,
 * and the next fetch reads the alert mails anyway.
 */
check: MailboxCheck | null, };
