// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortalCount } from "./PortalCount";

/**
 * "Postfach prüfen": the sign-in worked, and this many alert mails of the enabled portals
 * lie in the mailbox from the last `days` days (`mail::check::check_mailbox`; its errors
 * are the mail error codes).
 */
export type MailboxCheck = { days: number, total: number, 
/**
 * Every portal asked for, in the order of `Portal::ALL`.
 */
perPortal: Array<PortalCount>, };
