// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortalCount } from "./PortalCount";

/**
 * What the market brings.
 */
export type Market = { 
/**
 * New jobs per portal of the last [`RECENT_DAYS`] days (by the alert mail's date; a job
 * two portals announced counts for each), every portal in the order of `Portal::ALL`.
 */
newByPortal: Array<PortalCount>, 
/**
 * The median day rate in euros of the jobs scored high or medium in the last
 * [`OVERVIEW_DAYS`] days whose ad states one (an hourly rate x 8, other currencies
 * left out); `null` without any.
 */
medianDayRate: number | null, 
/**
 * How many rates the median is taken from.
 */
rateCount: number, 
/**
 * Of the jobs of the last [`OVERVIEW_DAYS`] days whose remote share is known (the ad's
 * share, else the location's work mode), the percentage that are at least half remote;
 * `null` without any.
 */
remoteShare: number | null, 
/**
 * How many jobs the remote share is taken from.
 */
remoteKnown: number, };
