// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Band } from "./Band";
import type { Highlight } from "./Highlight";
import type { MatchStatus } from "./MatchStatus";
import type { Notice } from "./Notice";
import type { Reason } from "./Reason";

/**
 * The full match explanation of one job (reader).
 */
export type MatchDetail = { score: number, status: MatchStatus, band: Band, 
/**
 * Revision of engine, profile and model the score was made with.
 */
rev: string, at: string, summary: Notice | null, 
/**
 * At most 40.
 */
reasons: Array<Reason>, 
/**
 * At most 200.
 */
highlights: Array<Highlight>, 
/**
 * The hard criteria strip.
 */
criteria: Array<Reason>, 
/**
 * What moved the score, at most five lines in reading order ("Warum diese Zahl?"):
 * codes `musts`, `nice`, `focus`, `targetRole`, `wishes`, `evidence`, `permanent`,
 * `cap` with their params (`matching::FactorCode`).
 */
factors: Array<Notice>, };
