// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A must requirement open in `count` jobs.
 */
export type OpenMust = { label: string, count: number, };
