// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a job came to the list (the list's filter "Herkunft"): an alert mail named it, or the
 * app's own search found it. A job can have both.
 */
export type Origin = "mail" | "search";
