// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Market } from "./Market";
import type { OpenMust } from "./OpenMust";
import type { QuietPortal } from "./QuietPortal";

/**
 * The numbers of the "Übersicht" page, from one call ([`overview_stats`]).
 */
export type OverviewStats = { 
/**
 * The must requirements most often open in the scored jobs of the inbox of the last
 * [`OVERVIEW_DAYS`] days: at most five, each open in at least two jobs, the most
 * frequent first (the ad's words of the first one seen).
 */
openMusts: Array<OpenMust>, market: Market, 
/**
 * Every enabled portal (in the order of `Portal::ALL`) with its last alert mail.
 */
quietPortals: Array<QuietPortal>, 
/**
 * Jobs of the inbox whose full ad "Details holen" can still fetch: not fetched yet or
 * failed so far, of an enabled portal with its details switched on; one with only the
 * teaser where the sign-in is switched on too. Ads that are gone or given up on are
 * none of them.
 */
detailsWanted: number, 
/**
 * Excluded jobs of the inbox not opened yet.
 */
excludedNew: number, };
