// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The app's colour palettes (`ui/src/styles/tokens.css`): Coast (cream, coral and navy) by
 * default, GitHub's light and dark Primer colours.
 */
export type Palette = "coast" | "light" | "dark";
