// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The app's colour palettes (`ui/src/styles/tokens.css`): CXact by default (the cxpertise
 * cream, coral and navy), and Light and Dark, neutral with blue details.
 */
export type Palette = "cxact" | "light" | "dark";
