// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The app's colour palettes (`ui/src/styles/tokens.css`): Light by default and Dark, neutral
 * with one blue accent.
 */
export type Palette = "light" | "dark";
