// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Portal } from "./Portal";
import type { PortalHealth } from "./PortalHealth";
import type { PortalLogin } from "./PortalLogin";
import type { Quota } from "./Quota";
import type { Way } from "./Way";

/**
 * A portal in the settings.
 */
export type PortalState = { portal: Portal, 
/**
 * How the app gets its jobs: its own search, or alert mails (the cards of Einstellungen).
 */
way: Way, 
/**
 * Its alert mails are read and its ads fetched.
 */
enabled: boolean, login: PortalLogin, loginEnabled: boolean, 
/**
 * `null` = unknown (or no sign-in), `false` = sign-in needed.
 */
signedIn: boolean | null, health: PortalHealth, 
/**
 * The user has to act on the health ([`PortalHealth::action_needed`]).
 */
actionNeeded: boolean, quota: Quota | null, 
/**
 * The date of its last alert mail the app read (`null`: none yet); the settings warn
 * when it is long ago.
 */
lastAlert: string | null, };
