// Generated by core/src/view/ts.rs from the portal registry, core/src/portal (cargo test -p jobalert-core ipc_types). Do not edit.
import type { Portal } from "./Portal";

/** Every portal in the app's order (`Portal::ALL`). */
export const PORTALS: readonly Portal[] = ["linkedin", "freelance", "freelancermap", "hays", "michaelpage", "solcom", "gulp", "interimx"];

/** A portal's name everywhere: its web address (`Portal::label`). */
export const PORTAL_LABEL: Record<Portal, string> = {
  linkedin: "linkedin.com",
  freelance: "freelance.de",
  freelancermap: "freelancermap.de",
  hays: "hays.de",
  michaelpage: "michaelpage.de",
  solcom: "solcom.de",
  gulp: "gulp.de",
  interimx: "interim-x.com",
};

/** A portal's two-letter mark, brand-neutral (`Portal::monogram`). */
export const PORTAL_MONOGRAM: Record<Portal, string> = {
  linkedin: "in",
  freelance: "fd",
  freelancermap: "fm",
  hays: "Ha",
  michaelpage: "MP",
  solcom: "so",
  gulp: "gu",
  interimx: "ix",
};
