// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Portal } from "./Portal";

/**
 * A number of a portal.
 */
export type PortalCount = { portal: Portal, count: number, };
