// Generated by core/src/view/ts.rs from core/src/profile/form.rs (cargo test -p jobalert-core ipc_types). Do not edit.
import type { ProfileForm } from "./ProfileForm";
import type { UnreadableField } from "./UnreadableField";

/** The unit a number criterion is shown with (the catalog's `profile.unit`). */
export type CriterionUnit = "euro" | "experience" | "percent" | "days" | "months";

/** The number criteria of the form: the largest value the backend takes, the unit. */
export const NUMBER_CRITERIA = {
  minDayRate: { max: 100000, unit: "euro" },
  targetYears: { max: 70, unit: "experience" },
  minSalary: { max: 10000000, unit: "euro" },
  permanentRemoteMin: { max: 100, unit: "percent" },
  workloadMinDays: { max: 5, unit: "days" },
  workloadMaxDays: { max: 5, unit: "days" },
  minMonths: { max: 120, unit: "months" },
} as const satisfies Record<string, { max: number; unit: CriterionUnit }>;
export type NumberCriterion = keyof typeof NUMBER_CRITERIA;

/** The word criteria of the form (`upper`: codes in capitals). */
export const WORD_CRITERIA = {
  countries: { upper: true },
  permanentPlaces: { upper: false },
  exclusionWords: { upper: false },
} as const satisfies Record<string, { upper: boolean }>;
export type WordCriterion = keyof typeof WORD_CRITERIA;

/** Every field whose value of the file can be removed on its own. */
export const UNREADABLE_FIELDS: readonly UnreadableField[] = ["minDayRate", "countries", "contracts", "remoteOutside", "available", "targetYears", "minSalary", "permanentPlaces", "permanentRemoteMin", "focus", "roles", "wishDayRate", "remote", "regions", "wishIndustries", "workloadMinDays", "workloadMaxDays", "minMonths", "exclusionWords"];

/** At most this many competences are Schwerpunkte. */
export const MAX_FOCUS = 5;
/** The most years of experience, in total and per competence. */
export const MAX_YEARS = 70;
/** The most entries of a list, and characters of an entry. */
export const MAX_ITEMS = 300;
export const MAX_TEXT = 1000;

/** The empty form (`ProfileForm::default()`). */
export const EMPTY_FORM: ProfileForm = {
  "name": "",
  "title": "",
  "competences": [],
  "strengths": [],
  "keywords": [],
  "years": null,
  "degrees": [],
  "industries": [],
  "tools": [],
  "certificates": [],
  "languages": [],
  "focus": [],
  "roles": [],
  "wishes": {
    "dayRate": null,
    "remote": null,
    "regions": [],
    "industries": []
  },
  "criteria": {
    "minDayRate": null,
    "countries": [],
    "noAnue": false,
    "noPermanent": false,
    "available": {
      "kind": "unset"
    },
    "remoteOutside": true,
    "targetYears": null,
    "minSalary": null,
    "permanentPlaces": [],
    "permanentRemoteMin": null,
    "workloadMinDays": null,
    "workloadMaxDays": null,
    "minMonths": null,
    "exclusionWords": []
  }
};
