// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A profile of the work folder as the switcher of the Profil view lists it (one of them
 * active; `profile::list`).
 */
export type ProfileEntry = { 
/**
 * Its number (`beraterprofil.json` is 1); the page's "Profil 2" without a name or role.
 */
id: number, 
/**
 * The name the user gave it ("Umbenennen").
 */
name: string | null, 
/**
 * Its role (`titel`, else its first `wunschrollen`): its name without one of its own.
 */
role: string | null, active: boolean, };
