// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Portal } from "./Portal";

/**
 * A portal and its last alert mail; `quiet` when there was none in the last
 * [`RECENT_DAYS`] days (or never).
 */
export type QuietPortal = { portal: Portal, lastAlert: string | null, quiet: boolean, };
