// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Quota = { 
/**
 * Requests in the last hour and the hourly cap.
 */
usedHour: number, capHour: number, 
/**
 * Requests today (since local midnight) and the daily cap.
 */
usedDay: number, capDay: number, };
