// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKey } from "./JobKey";
import type { Origin } from "./Origin";

/**
 * What the interface starts. The JSON is flat: `{ "kind": "details", "keys": [...] }`.
 */
export type RunRequest = { 
/**
 * A fetch of one way only (user decision 2026-10-01: the button fetches what is shown):
 * the search ("Jetzt suchen") or the alert mails ("Postfach abrufen"); `None`, every way.
 */
only?: Origin, } & ({ "kind": "fetch" } | { "kind": "details", keys: Array<JobKey>, } | { "kind": "rescore" });
