// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreDelta } from "./ScoreDelta";

/**
 * Counters of the score step.
 */
export type ScoreSummary = { scored: number, excluded: number, unscorable: number, 
/**
 * Jobs still waiting for a score.
 */
pending: number, best: number | null, 
/**
 * A rescore (after the profile was saved) only: the excluded and the high-band jobs of
 * the inbox before and after it.
 */
delta: ScoreDelta | null, };
