// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a rescore changed: the excluded and the high-band jobs of the inbox (no duplicate)
 * before and after it.
 */
export type ScoreDelta = { excludedBefore: number, excludedAfter: number, highBefore: number, highAfter: number, };
