// Generated by core/src/view/ts.rs from core/src/settings.rs (cargo test -p jobalert-core ipc_types). Do not edit.

/** Days after which old jobs archive themselves when the switch is on. */
export const AUTO_ARCHIVE_DAYS = 30;
/** Days after which the trash empties itself when the switch is on. */
export const AUTO_EMPTY_TRASH_DAYS = 30;
