// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FetchRange } from "./FetchRange";
import type { Language } from "./Language";
import type { Palette } from "./Palette";
import type { PortalPatch } from "./PortalPatch";

/**
 * Changes of the settings. `null` = unchanged; the workspace only changes through the
 * folder dialog (`pick_workspace`).
 */
export type SettingsPatch = { portals: Array<PortalPatch>, 
/**
 * Which alert mails "Postfach abrufen" reads.
 */
fetchRange: FetchRange | null, 
/**
 * Write the Excel file with every export.
 */
exportExcel: boolean | null, 
/**
 * Write the CSV file with every export.
 */
exportCsv: boolean | null, 
/**
 * Fetch by itself at the start and every four hours.
 */
autoFetch: boolean | null, 
/**
 * "Jobs abrufen" reads the alert mails.
 */
fetchMail: boolean | null, 
/**
 * "Jobs abrufen" searches the sources.
 */
fetchSearch: boolean | null, 
/**
 * The language the user chose (from then on the OS language no longer counts).
 */
language: Language | null, 
/**
 * The palette the user chose (Einstellungen, Darstellung).
 */
palette: Palette | null, };
