// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsView = { 
/**
 * Effective workspace (chosen or default).
 */
workspace: string, workspaceIsDefault: boolean, 
/**
 * The Excel file of the overview, where it is or will be written.
 */
excelPath: string, 
/**
 * The Excel file is there to open: written (`exportExcel` on) and on disk.
 */
excelExists: boolean, };
