// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsView = { 
/**
 * Effective workspace (chosen or default).
 */
workspace: string, workspaceIsDefault: boolean, };
