// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";
import type { Palette } from "./Palette";
import type { PortalPatch } from "./PortalPatch";

/**
 * Changes of the settings. `null` = unchanged; the workspace only changes through the
 * folder dialog (`pick_workspace`).
 */
export type SettingsPatch = { portals: Array<PortalPatch>, 
/**
 * Days after which old jobs archive themselves; 0 = never (`null` = unchanged).
 */
autoArchiveDays: number | null, 
/**
 * Days after which the trash empties itself; 0 = never (`null` = unchanged).
 */
autoEmptyTrashDays: number | null, 
/**
 * The language the user chose (from then on the OS language no longer counts).
 */
language: Language | null, 
/**
 * The palette the user chose (Einstellungen, Darstellung).
 */
palette: Palette | null, };
