// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The field of the profile a term goes into.
 */
export type TermField = "competence" | "tool" | "industry" | "language" | "certificate" | "degree";
