// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextRange } from "./TextRange";

/**
 * How the reader lays out the ad's text (UTF-16 ranges of `JobDetail::text`).
 */
export type TextLayout = { 
/**
 * The words of a line that heads a section of the ad.
 */
headings: Array<TextRange>, 
/**
 * The bullet glyph of a list line and the space after it (the item follows).
 */
bullets: Array<TextRange>, };
