// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The terms of the suggestions, each list sorted and without doubles (in any case).
 */
export type Vocabulary = { 
/**
 * Skills, methods, tools and roles: competences, their synonyms, tools, keywords.
 */
skills: Array<string>, 
/**
 * Industries: the profile's industries and the wished ones.
 */
industries: Array<string>, };
