// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the app gets a source's jobs (user decision 2026-10-01: one way each).
 */
export type Way = "search" | "alert";
