// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceProfile } from "./WorkspaceProfile";

/**
 * Another work folder (`pick_workspace`): the folder, and what became of the profile there.
 */
export type WorkspacePick = { folder: string, profile: WorkspaceProfile, };
