// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The profile after a change of the work folder.
 */
export type WorkspaceProfile = "copied" | "own" | "none";
