//! Generated by tools/tokens.mjs from ui/src/styles/tokens.css, do not edit: change
//! tokens.css and run `npm run regen` (docs/CHANGING.md, "Change the look").
//!
//! The colours of the app that something besides the page wears: the Excel file, the
//! window (src-tauri) and the app icon. Each constant is a colour token of tokens.css,
//! resolved to its palette entry (the doc comment names the chain);
//! `core/tests/palette.rs` fails when this file no longer says what tokens.css says.

pub use super::colour::Colour;

/// `--bg` (`--p-cream`).
pub const BG: Colour = Colour::new("hsl(60 6.7% 97.1%)", [0xF8, 0xF8, 0xF7]);
/// `--surface-muted` (`--p-muted`).
pub const SURFACE_MUTED: Colour = Colour::new("hsl(60 4.3% 95.5%)", [0xF4, 0xF4, 0xF3]);
/// `--score-ring-0` (`--p-score-red`).
pub const SCORE_RING_0: Colour = Colour::new("hsl(358 75% 59%)", [0xE5, 0x48, 0x4D]);
/// `--score-ring-1` (`--p-score-red`).
pub const SCORE_RING_1: Colour = Colour::new("hsl(358 75% 59%)", [0xE5, 0x48, 0x4D]);
/// `--score-ring-2` (`--p-score-orange`).
pub const SCORE_RING_2: Colour = Colour::new("hsl(24 87% 56%)", [0xF0, 0x7B, 0x2D]);
/// `--score-ring-3` (`--p-score-orange`).
pub const SCORE_RING_3: Colour = Colour::new("hsl(24 87% 56%)", [0xF0, 0x7B, 0x2D]);
/// `--score-ring-4` (`--p-score-yellow`).
pub const SCORE_RING_4: Colour = Colour::new("hsl(40 88% 59%)", [0xF2, 0xB5, 0x3A]);
/// `--score-ring-5` (`--p-score-yellow`).
pub const SCORE_RING_5: Colour = Colour::new("hsl(40 88% 59%)", [0xF2, 0xB5, 0x3A]);
/// `--score-ring-6` (`--p-score-lime`).
pub const SCORE_RING_6: Colour = Colour::new("hsl(83 44% 51%)", [0x8F, 0xB9, 0x4B]);
/// `--score-ring-7` (`--p-score-lime`).
pub const SCORE_RING_7: Colour = Colour::new("hsl(83 44% 51%)", [0x8F, 0xB9, 0x4B]);
/// `--score-ring-8` (`--p-score-green`).
pub const SCORE_RING_8: Colour = Colour::new("hsl(139 44% 44%)", [0x3F, 0xA2, 0x5E]);
/// `--score-ring-9` (`--p-score-green`).
pub const SCORE_RING_9: Colour = Colour::new("hsl(139 44% 44%)", [0x3F, 0xA2, 0x5E]);
/// `--score-excluded` (`--text-subtle`, `--p-fg-subtle`).
pub const SCORE_EXCLUDED: Colour = Colour::new("hsl(60 1.4% 40.6%)", [0x69, 0x69, 0x66]);
/// `--brand` (`--p-brand`).
pub const BRAND: Colour = Colour::new("hsl(240 15.8% 7.5%)", [0x10, 0x10, 0x16]);
/// `--brand-glyph` (`--p-brand-glyph`).
pub const BRAND_GLYPH: Colour = Colour::new("hsl(0 0% 100%)", [0xFF, 0xFF, 0xFF]);

/// `--score-ring-0` ... `--score-ring-9` in order.
pub const SCORE_RING: [Colour; 10] = [
    SCORE_RING_0,
    SCORE_RING_1,
    SCORE_RING_2,
    SCORE_RING_3,
    SCORE_RING_4,
    SCORE_RING_5,
    SCORE_RING_6,
    SCORE_RING_7,
    SCORE_RING_8,
    SCORE_RING_9,
];

/// Every colour constant above by the name of its token (without the dashes).
pub const TOKENS: [(&str, Colour); 15] = [
    ("bg", BG),
    ("surface-muted", SURFACE_MUTED),
    ("score-ring-0", SCORE_RING_0),
    ("score-ring-1", SCORE_RING_1),
    ("score-ring-2", SCORE_RING_2),
    ("score-ring-3", SCORE_RING_3),
    ("score-ring-4", SCORE_RING_4),
    ("score-ring-5", SCORE_RING_5),
    ("score-ring-6", SCORE_RING_6),
    ("score-ring-7", SCORE_RING_7),
    ("score-ring-8", SCORE_RING_8),
    ("score-ring-9", SCORE_RING_9),
    ("score-excluded", SCORE_EXCLUDED),
    ("brand", BRAND),
    ("brand-glyph", BRAND_GLYPH),
];

// The window's colour in the other palettes (`:root[data-palette='…']`): `--bg`, which the
// window wears before the page paints (Light's is above).
/// `--bg` of dark (`--p-cream`).
pub const DARK_BG: Colour = Colour::new("hsl(180 3.2% 6.1%)", [0x0F, 0x10, 0x10]);

/// The constants above by palette and token.
pub const WINDOW_PALETTES: [(&str, &str, Colour); 1] = [("dark", "bg", DARK_BG)];
