//! Generated by tools/tokens.mjs from ui/src/styles/tokens.css, do not edit: change
//! tokens.css and run `npm run regen` (docs/CHANGING.md, "Change the look").
//!
//! The colours of the app that something besides the page wears: the Excel file, the
//! window and the Windows title bar (src-tauri) and the app icon. Each constant is a colour
//! token of tokens.css, resolved to its palette entry (the doc comment names the chain);
//! `core/tests/palette.rs` fails when this file no longer says what tokens.css says.

pub use super::colour::Colour;

/// `--bg` (`--p-cream`).
pub const BG: Colour = Colour::new("hsl(32 50% 94.5%)", [0xF8, 0xF1, 0xEA]);
/// `--surface-muted` (`--p-muted`).
pub const SURFACE_MUTED: Colour = Colour::new("hsl(33 40% 95.5%)", [0xF8, 0xF4, 0xEF]);
/// `--text` (`--p-ink`).
pub const TEXT: Colour = Colour::new("hsl(45 7% 17%)", [0x2E, 0x2D, 0x28]);
/// `--text-subtle` (`--p-fg-subtle`).
pub const TEXT_SUBTLE: Colour = Colour::new("hsl(30 5% 42%)", [0x70, 0x6B, 0x66]);
/// `--score-ring-0` (`--p-score-0`).
pub const SCORE_RING_0: Colour = Colour::new("hsl(4 62% 58%)", [0xD6, 0x5A, 0x51]);
/// `--score-ring-1` (`--p-score-1`).
pub const SCORE_RING_1: Colour = Colour::new("hsl(13 69% 58%)", [0xDE, 0x6A, 0x4A]);
/// `--score-ring-2` (`--p-score-2`).
pub const SCORE_RING_2: Colour = Colour::new("hsl(19 75% 58%)", [0xE4, 0x76, 0x44]);
/// `--score-ring-3` (`--p-score-3`).
pub const SCORE_RING_3: Colour = Colour::new("hsl(25 79% 58%)", [0xE9, 0x86, 0x3F]);
/// `--score-ring-4` (`--p-score-4`).
pub const SCORE_RING_4: Colour = Colour::new("hsl(33 80% 58%)", [0xEA, 0x9C, 0x3E]);
/// `--score-ring-5` (`--p-score-5`).
pub const SCORE_RING_5: Colour = Colour::new("hsl(40 77% 59%)", [0xE7, 0xB1, 0x46]);
/// `--score-ring-6` (`--p-score-6`).
pub const SCORE_RING_6: Colour = Colour::new("hsl(51 58% 54%)", [0xCE, 0xB9, 0x46]);
/// `--score-ring-7` (`--p-score-7`).
pub const SCORE_RING_7: Colour = Colour::new("hsl(68 43% 49%)", [0xA4, 0xB3, 0x47]);
/// `--score-ring-8` (`--p-score-8`).
pub const SCORE_RING_8: Colour = Colour::new("hsl(96 35% 50%)", [0x77, 0xAC, 0x53]);
/// `--score-ring-9` (`--p-score-9`).
pub const SCORE_RING_9: Colour = Colour::new("hsl(140 41% 45%)", [0x44, 0xA2, 0x63]);
/// `--score-excluded` (`--text-subtle`, `--p-fg-subtle`).
pub const SCORE_EXCLUDED: Colour = TEXT_SUBTLE;
/// `--brand` (`--p-coral`).
pub const BRAND: Colour = Colour::new("hsl(13 78% 57%)", [0xE7, 0x61, 0x3C]);
/// `--brand-glyph` (`--p-white`).
pub const BRAND_GLYPH: Colour = Colour::new("hsl(0 0% 100%)", [0xFF, 0xFF, 0xFF]);

/// `--score-ring-0` ... `--score-ring-9` in order.
pub const SCORE_RING: [Colour; 10] = [
    SCORE_RING_0,
    SCORE_RING_1,
    SCORE_RING_2,
    SCORE_RING_3,
    SCORE_RING_4,
    SCORE_RING_5,
    SCORE_RING_6,
    SCORE_RING_7,
    SCORE_RING_8,
    SCORE_RING_9,
];

/// Every colour constant above by the name of its token (without the dashes).
pub const TOKENS: [(&str, Colour); 17] = [
    ("bg", BG),
    ("surface-muted", SURFACE_MUTED),
    ("text", TEXT),
    ("text-subtle", TEXT_SUBTLE),
    ("score-ring-0", SCORE_RING_0),
    ("score-ring-1", SCORE_RING_1),
    ("score-ring-2", SCORE_RING_2),
    ("score-ring-3", SCORE_RING_3),
    ("score-ring-4", SCORE_RING_4),
    ("score-ring-5", SCORE_RING_5),
    ("score-ring-6", SCORE_RING_6),
    ("score-ring-7", SCORE_RING_7),
    ("score-ring-8", SCORE_RING_8),
    ("score-ring-9", SCORE_RING_9),
    ("score-excluded", SCORE_EXCLUDED),
    ("brand", BRAND),
    ("brand-glyph", BRAND_GLYPH),
];

// The window's colours in the other palettes (`:root[data-palette='…']`): `--bg`, `--text`
// and `--text-subtle`, which the window and the Windows title bar wear (Coast's are above).
/// `--bg` of light (`--p-cream`).
pub const LIGHT_BG: Colour = Colour::new("hsl(210 28.6% 97.3%)", [0xF6, 0xF8, 0xFA]);
/// `--text` of light (`--p-ink`).
pub const LIGHT_TEXT: Colour = Colour::new("hsl(213 13% 14%)", [0x1F, 0x23, 0x28]);
/// `--text-subtle` of light (`--p-fg-subtle`).
pub const LIGHT_TEXT_SUBTLE: Colour = Colour::new("hsl(212 8% 43%)", [0x65, 0x6D, 0x76]);
/// `--bg` of dark (`--p-cream`).
pub const DARK_BG: Colour = Colour::new("hsl(218 80% 2%)", [0x01, 0x04, 0x09]);
/// `--text` of dark (`--p-ink`).
pub const DARK_TEXT: Colour = Colour::new("hsl(210 66.7% 96.5%)", [0xF0, 0xF6, 0xFC]);
/// `--text-subtle` of dark (`--p-fg-subtle`).
pub const DARK_TEXT_SUBTLE: Colour = Colour::new("hsl(214 8% 55%)", [0x83, 0x8B, 0x95]);

/// The constants above by palette and token.
pub const WINDOW_PALETTES: [(&str, &str, Colour); 6] = [
    ("light", "bg", LIGHT_BG),
    ("light", "text", LIGHT_TEXT),
    ("light", "text-subtle", LIGHT_TEXT_SUBTLE),
    ("dark", "bg", DARK_BG),
    ("dark", "text", DARK_TEXT),
    ("dark", "text-subtle", DARK_TEXT_SUBTLE),
];
