//! Generated by tools/tokens.mjs from ui/src/styles/tokens.css, do not edit: change
//! tokens.css and run `npm run regen` (docs/CHANGING.md, "Change the look").
//!
//! The colours of the app for everything that is not the page: the report, the Excel file
//! and the Windows title bar (src-tauri). Each constant is a colour token of tokens.css,
//! resolved to its palette entry (the doc comment names the chain); `core/tests/palette.rs`
//! fails when this file no longer says what tokens.css says.

pub use super::colour::Colour;

/// `--bg` (`--p-cream`).
pub const BG: Colour = Colour::new("hsl(32 33% 96%)", [0xF8, 0xF5, 0xF1]);
/// `--surface` (`--p-white`).
pub const SURFACE: Colour = Colour::new("hsl(0 0% 100%)", [0xFF, 0xFF, 0xFF]);
/// `--surface-muted` (`--p-muted`).
pub const SURFACE_MUTED: Colour = Colour::new("hsl(45 23% 95%)", [0xF5, 0xF4, 0xEF]);
/// `--surface-selected` (`--p-coral-25`).
pub const SURFACE_SELECTED: Colour = Colour::new("hsl(22 72% 96.5%)", [0xFD, 0xF4, 0xF0]);
/// `--surface-selected-hover` (`--p-coral-50`).
pub const SURFACE_SELECTED_HOVER: Colour = Colour::new("hsl(21 68% 94.5%)", [0xFB, 0xEE, 0xE7]);
/// `--surface-selected-press` (`--p-coral-70`).
pub const SURFACE_SELECTED_PRESS: Colour = Colour::new("hsl(21 68% 93%)", [0xF9, 0xEA, 0xE1]);
/// `--surface-inverse` (`--p-navy-deep`).
pub const SURFACE_INVERSE: Colour = Colour::new("hsl(212 30% 26%)", [0x2E, 0x41, 0x56]);
/// `--text` (`--p-ink`).
pub const TEXT: Colour = Colour::new("hsl(45 7% 17%)", [0x2E, 0x2D, 0x28]);
/// `--text-muted` (`--p-muted-fg`).
pub const TEXT_MUTED: Colour = Colour::new("hsl(30 4% 35%)", [0x5D, 0x59, 0x56]);
/// `--text-subtle` (`--p-fg-subtle`).
pub const TEXT_SUBTLE: Colour = Colour::new("hsl(30 4% 43%)", [0x72, 0x6E, 0x69]);
/// `--text-heading` (`--p-navy`).
pub const TEXT_HEADING: Colour = Colour::new("hsl(212 34% 37%)", [0x3E, 0x5C, 0x7E]);
/// `--text-label` (`--p-navy`).
pub const TEXT_LABEL: Colour = Colour::new("hsl(212 34% 37%)", [0x3E, 0x5C, 0x7E]);
/// `--text-on-accent` (`--p-on-accent`).
pub const TEXT_ON_ACCENT: Colour = Colour::new("hsl(0 0% 98%)", [0xFA, 0xFA, 0xFA]);
/// `--text-inverse` (`--p-white`).
pub const TEXT_INVERSE: Colour = Colour::new("hsl(0 0% 100%)", [0xFF, 0xFF, 0xFF]);
/// `--link` (`--p-navy`).
pub const LINK: Colour = Colour::new("hsl(212 34% 37%)", [0x3E, 0x5C, 0x7E]);
/// `--link-hover` (`--p-navy-deep`).
pub const LINK_HOVER: Colour = Colour::new("hsl(212 30% 26%)", [0x2E, 0x41, 0x56]);
/// `--border` (`--p-line`).
pub const BORDER: Colour = Colour::new("hsl(45 22% 90%)", [0xEB, 0xE8, 0xE0]);
/// `--border-strong` (`--p-border-strong`).
pub const BORDER_STRONG: Colour = Colour::new("hsl(40 12% 78%)", [0xCE, 0xC9, 0xC0]);
/// `--border-input` (`--p-border-input`).
pub const BORDER_INPUT: Colour = Colour::new("hsl(40 10% 66%)", [0xB1, 0xAB, 0xA0]);
/// `--border-navy` (`--p-navy-200`).
pub const BORDER_NAVY: Colour = Colour::new("hsl(212 26% 84%)", [0xCC, 0xD5, 0xE1]);
/// `--accent` (`--p-coral`).
pub const ACCENT: Colour = Colour::new("hsl(13 73% 63%)", [0xE6, 0x7A, 0x5C]);
/// `--accent-soft` (`--p-accent-soft`).
pub const ACCENT_SOFT: Colour = Colour::new("hsl(20 62% 91%)", [0xF6, 0xE3, 0xDA]);
/// `--accent-text` (`--p-coral-800`).
pub const ACCENT_TEXT: Colour = Colour::new("hsl(13 62% 42%)", [0xAE, 0x45, 0x29]);
/// `--primary` (`--p-coral`).
pub const PRIMARY: Colour = Colour::new("hsl(13 73% 63%)", [0xE6, 0x7A, 0x5C]);
/// `--primary-hover` (`--p-coral-variant`).
pub const PRIMARY_HOVER: Colour = Colour::new("hsl(13 64% 56%)", [0xD7, 0x66, 0x47]);
/// `--primary-active` (`--p-coral-press`).
pub const PRIMARY_ACTIVE: Colour = Colour::new("hsl(13 58% 50%)", [0xC9, 0x56, 0x36]);
/// `--toggle-off` (`--p-border-strong`).
pub const TOGGLE_OFF: Colour = Colour::new("hsl(40 12% 78%)", [0xCE, 0xC9, 0xC0]);
/// `--toggle-off-hover` (`--p-border-input`).
pub const TOGGLE_OFF_HOVER: Colour = Colour::new("hsl(40 10% 66%)", [0xB1, 0xAB, 0xA0]);
/// `--toggle-off-press` (`--p-border-press`).
pub const TOGGLE_OFF_PRESS: Colour = Colour::new("hsl(40 10% 58%)", [0x9F, 0x97, 0x89]);
/// `--toggle-on` (`--p-coral`).
pub const TOGGLE_ON: Colour = Colour::new("hsl(13 73% 63%)", [0xE6, 0x7A, 0x5C]);
/// `--toggle-on-hover` (`--p-coral-variant`).
pub const TOGGLE_ON_HOVER: Colour = Colour::new("hsl(13 64% 56%)", [0xD7, 0x66, 0x47]);
/// `--toggle-on-press` (`--p-coral-press`).
pub const TOGGLE_ON_PRESS: Colour = Colour::new("hsl(13 58% 50%)", [0xC9, 0x56, 0x36]);
/// `--unread` (`--p-coral`).
pub const UNREAD: Colour = Colour::new("hsl(13 73% 63%)", [0xE6, 0x7A, 0x5C]);
/// `--ring-track-selected` (`--p-coral-150`).
pub const RING_TRACK_SELECTED: Colour = Colour::new("hsl(20 40% 88%)", [0xED, 0xDC, 0xD4]);
/// `--nav-active-bg` (`--p-white`).
pub const NAV_ACTIVE_BG: Colour = Colour::new("hsl(0 0% 100%)", [0xFF, 0xFF, 0xFF]);
/// `--nav-active-border` (`--p-line`).
pub const NAV_ACTIVE_BORDER: Colour = Colour::new("hsl(45 22% 90%)", [0xEB, 0xE8, 0xE0]);
/// `--nav-active-fg` (`--p-navy`).
pub const NAV_ACTIVE_FG: Colour = Colour::new("hsl(212 34% 37%)", [0x3E, 0x5C, 0x7E]);
/// `--nav-active-icon` (`--p-coral`).
pub const NAV_ACTIVE_ICON: Colour = Colour::new("hsl(13 73% 63%)", [0xE6, 0x7A, 0x5C]);
/// `--count-soft-bg` (`--p-coral-40`).
pub const COUNT_SOFT_BG: Colour = Colour::new("hsl(22 72% 95%)", [0xFB, 0xF0, 0xE9]);
/// `--count-soft-fg` (`--p-coral-800`).
pub const COUNT_SOFT_FG: Colour = Colour::new("hsl(13 62% 42%)", [0xAE, 0x45, 0x29]);
/// `--count-soft-hover` (`--p-coral-70`).
pub const COUNT_SOFT_HOVER: Colour = Colour::new("hsl(21 68% 93%)", [0xF9, 0xEA, 0xE1]);
/// `--icon-accent` (`--p-navy`).
pub const ICON_ACCENT: Colour = Colour::new("hsl(212 34% 37%)", [0x3E, 0x5C, 0x7E]);
/// `--active-surface` (`--p-navy-50`).
pub const ACTIVE_SURFACE: Colour = Colour::new("hsl(212 30% 96%)", [0xF2, 0xF5, 0xF8]);
/// `--active-edge` (`--p-navy`).
pub const ACTIVE_EDGE: Colour = Colour::new("hsl(212 34% 37%)", [0x3E, 0x5C, 0x7E]);
/// `--active-text` (`--p-navy-deep`).
pub const ACTIVE_TEXT: Colour = Colour::new("hsl(212 30% 26%)", [0x2E, 0x41, 0x56]);
/// `--active-hover` (`--p-navy-150`).
pub const ACTIVE_HOVER: Colour = Colour::new("hsl(212 30% 90%)", [0xDE, 0xE5, 0xED]);
/// `--meter-fill` (`--p-navy`).
pub const METER_FILL: Colour = Colour::new("hsl(212 34% 37%)", [0x3E, 0x5C, 0x7E]);
/// `--meter-track` (`--p-navy-100`).
pub const METER_TRACK: Colour = Colour::new("hsl(212 32% 93%)", [0xE7, 0xED, 0xF3]);
/// `--meter-warning` (`--p-score-mid`).
pub const METER_WARNING: Colour = Colour::new("hsl(38 55% 55%)", [0xCB, 0x9D, 0x4D]);
/// `--pressed` (`--p-navy-deep`).
pub const PRESSED: Colour = Colour::new("hsl(212 30% 26%)", [0x2E, 0x41, 0x56]);
/// `--focus` (`--p-navy`).
pub const FOCUS: Colour = Colour::new("hsl(212 34% 37%)", [0x3E, 0x5C, 0x7E]);
/// `--caret` (`--p-navy`).
pub const CARET: Colour = Colour::new("hsl(212 34% 37%)", [0x3E, 0x5C, 0x7E]);
/// `--success` (`--p-success`).
pub const SUCCESS: Colour = Colour::new("hsl(150 27% 60%)", [0x7D, 0xB5, 0x99]);
/// `--success-strong` (`--p-success-strong`).
pub const SUCCESS_STRONG: Colour = Colour::new("hsl(150 35% 33%)", [0x37, 0x72, 0x54]);
/// `--success-soft` (`--p-success-soft`).
pub const SUCCESS_SOFT: Colour = Colour::new("hsl(150 27% 94%)", [0xEC, 0xF4, 0xF0]);
/// `--warning` (`--p-warning`).
pub const WARNING: Colour = Colour::new("hsl(45 76% 75%)", [0xF0, 0xD7, 0x8F]);
/// `--warning-strong` (`--p-warning-strong`).
pub const WARNING_STRONG: Colour = Colour::new("hsl(38 70% 34%)", [0x93, 0x67, 0x1A]);
/// `--warning-soft` (`--p-warning-soft`).
pub const WARNING_SOFT: Colour = Colour::new("hsl(45 76% 93%)", [0xFB, 0xF4, 0xE0]);
/// `--danger` (`--p-danger`).
pub const DANGER: Colour = Colour::new("hsl(4 51% 56%)", [0xC8, 0x5D, 0x56]);
/// `--danger-strong` (`--p-danger-strong`).
pub const DANGER_STRONG: Colour = Colour::new("hsl(4 55% 45%)", [0xB2, 0x3C, 0x34]);
/// `--danger-soft` (`--p-danger-soft`).
pub const DANGER_SOFT: Colour = Colour::new("hsl(4 51% 95%)", [0xF9, 0xED, 0xEC]);
/// `--danger-hover` (`--p-danger-700`).
pub const DANGER_HOVER: Colour = Colour::new("hsl(4 55% 41%)", [0xA2, 0x37, 0x2F]);
/// `--danger-active` (`--p-danger-750`).
pub const DANGER_ACTIVE: Colour = Colour::new("hsl(4 56% 37%)", [0x93, 0x31, 0x2A]);
/// `--info` (`--p-navy`).
pub const INFO: Colour = Colour::new("hsl(212 34% 37%)", [0x3E, 0x5C, 0x7E]);
/// `--info-strong` (`--p-navy-deep`).
pub const INFO_STRONG: Colour = Colour::new("hsl(212 30% 26%)", [0x2E, 0x41, 0x56]);
/// `--info-soft` (`--p-navy-50`).
pub const INFO_SOFT: Colour = Colour::new("hsl(212 30% 96%)", [0xF2, 0xF5, 0xF8]);
/// `--score-ring-0` (`--p-score-0`).
pub const SCORE_RING_0: Colour = Colour::new("hsl(4 62% 58%)", [0xD6, 0x5A, 0x51]);
/// `--score-ring-1` (`--p-score-1`).
pub const SCORE_RING_1: Colour = Colour::new("hsl(13 69% 58%)", [0xDE, 0x6A, 0x4A]);
/// `--score-ring-2` (`--p-score-2`).
pub const SCORE_RING_2: Colour = Colour::new("hsl(19 75% 58%)", [0xE4, 0x76, 0x44]);
/// `--score-ring-3` (`--p-score-3`).
pub const SCORE_RING_3: Colour = Colour::new("hsl(25 79% 58%)", [0xE9, 0x86, 0x3F]);
/// `--score-ring-4` (`--p-score-4`).
pub const SCORE_RING_4: Colour = Colour::new("hsl(33 80% 58%)", [0xEA, 0x9C, 0x3E]);
/// `--score-ring-5` (`--p-score-5`).
pub const SCORE_RING_5: Colour = Colour::new("hsl(40 77% 59%)", [0xE7, 0xB1, 0x46]);
/// `--score-ring-6` (`--p-score-6`).
pub const SCORE_RING_6: Colour = Colour::new("hsl(51 58% 54%)", [0xCE, 0xB9, 0x46]);
/// `--score-ring-7` (`--p-score-7`).
pub const SCORE_RING_7: Colour = Colour::new("hsl(68 43% 49%)", [0xA4, 0xB3, 0x47]);
/// `--score-ring-8` (`--p-score-8`).
pub const SCORE_RING_8: Colour = Colour::new("hsl(96 35% 50%)", [0x77, 0xAC, 0x53]);
/// `--score-ring-9` (`--p-score-9`).
pub const SCORE_RING_9: Colour = Colour::new("hsl(140 41% 45%)", [0x44, 0xA2, 0x63]);
/// `--score-digits` (`--p-ink`).
pub const SCORE_DIGITS: Colour = Colour::new("hsl(45 7% 17%)", [0x2E, 0x2D, 0x28]);
/// `--score-high-ring` (`--p-score-high`).
pub const SCORE_HIGH_RING: Colour = Colour::new("hsl(150 32% 46%)", [0x50, 0x9B, 0x75]);
/// `--score-high-text` (`--p-score-high-text`).
pub const SCORE_HIGH_TEXT: Colour = Colour::new("hsl(152 50% 31%)", [0x28, 0x77, 0x52]);
/// `--score-high-surface` (`--p-score-high-soft`).
pub const SCORE_HIGH_SURFACE: Colour = Colour::new("hsl(150 27% 93%)", [0xE8, 0xF2, 0xED]);
/// `--score-mid-ring` (`--p-score-mid`).
pub const SCORE_MID_RING: Colour = Colour::new("hsl(38 55% 55%)", [0xCB, 0x9D, 0x4D]);
/// `--score-mid-text` (`--p-warning-strong`).
pub const SCORE_MID_TEXT: Colour = Colour::new("hsl(38 70% 34%)", [0x93, 0x67, 0x1A]);
/// `--score-mid-surface` (`--p-warning-soft`).
pub const SCORE_MID_SURFACE: Colour = Colour::new("hsl(45 76% 93%)", [0xFB, 0xF4, 0xE0]);
/// `--score-low-ring` (`--p-score-low`).
pub const SCORE_LOW_RING: Colour = Colour::new("hsl(30 5% 56%)", [0x94, 0x8F, 0x89]);
/// `--score-low-text` (`--p-score-low-text`).
pub const SCORE_LOW_TEXT: Colour = Colour::new("hsl(30 4% 42%)", [0x6F, 0x6B, 0x67]);
/// `--score-low-surface` (`--p-muted`).
pub const SCORE_LOW_SURFACE: Colour = Colour::new("hsl(45 23% 95%)", [0xF5, 0xF4, 0xEF]);
/// `--score-track` (`--p-line`).
pub const SCORE_TRACK: Colour = Colour::new("hsl(45 22% 90%)", [0xEB, 0xE8, 0xE0]);
/// `--score-excluded` (`--text-subtle`, `--p-fg-subtle`).
pub const SCORE_EXCLUDED: Colour = TEXT_SUBTLE;
/// `--score-excluded-track` (`--score-track`, `--p-line`).
pub const SCORE_EXCLUDED_TRACK: Colour = SCORE_TRACK;
/// `--brand` (`--p-coral`).
pub const BRAND: Colour = Colour::new("hsl(13 73% 63%)", [0xE6, 0x7A, 0x5C]);
/// `--brand-glyph` (`--p-white`).
pub const BRAND_GLYPH: Colour = Colour::new("hsl(0 0% 100%)", [0xFF, 0xFF, 0xFF]);
/// `--border-focus` (`--p-navy`).
pub const BORDER_FOCUS: Colour = Colour::new("hsl(212 34% 37%)", [0x3E, 0x5C, 0x7E]);
/// `--control-hover` (`--surface-muted`, `--p-muted`).
pub const CONTROL_HOVER: Colour = SURFACE_MUTED;
/// `--control-hover-edge` (`--border-input`, `--p-border-input`).
pub const CONTROL_HOVER_EDGE: Colour = BORDER_INPUT;
/// `--raised-hover-edge` (`--border-navy`, `--p-navy-200`).
pub const RAISED_HOVER_EDGE: Colour = BORDER_NAVY;
/// `--raised-press` (`--surface-muted`, `--p-muted`).
pub const RAISED_PRESS: Colour = SURFACE_MUTED;
/// `--label-hover` (`--text`, `--p-ink`).
pub const LABEL_HOVER: Colour = TEXT;
/// `--label-press` (`--pressed`, `--p-navy-deep`).
pub const LABEL_PRESS: Colour = PRESSED;
/// `--label-glyph-hover` (`--icon-accent`, `--p-navy`).
pub const LABEL_GLYPH_HOVER: Colour = ICON_ACCENT;
/// `--grip-rest` (`--border-strong`, `--p-border-strong`).
pub const GRIP_REST: Colour = BORDER_STRONG;
/// `--grip-drag` (`--text-subtle`, `--p-fg-subtle`).
pub const GRIP_DRAG: Colour = TEXT_SUBTLE;

/// `--score-ring-0` ... `--score-ring-9` in order.
pub const SCORE_RING: [Colour; 10] = [
    SCORE_RING_0,
    SCORE_RING_1,
    SCORE_RING_2,
    SCORE_RING_3,
    SCORE_RING_4,
    SCORE_RING_5,
    SCORE_RING_6,
    SCORE_RING_7,
    SCORE_RING_8,
    SCORE_RING_9,
];

/// `--font-sans`.
pub const FONT_SANS: &str = "'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif";

/// Every colour constant above by the name of its token (without the dashes).
pub const TOKENS: [(&str, Colour); 101] = [
    ("bg", BG),
    ("surface", SURFACE),
    ("surface-muted", SURFACE_MUTED),
    ("surface-selected", SURFACE_SELECTED),
    ("surface-selected-hover", SURFACE_SELECTED_HOVER),
    ("surface-selected-press", SURFACE_SELECTED_PRESS),
    ("surface-inverse", SURFACE_INVERSE),
    ("text", TEXT),
    ("text-muted", TEXT_MUTED),
    ("text-subtle", TEXT_SUBTLE),
    ("text-heading", TEXT_HEADING),
    ("text-label", TEXT_LABEL),
    ("text-on-accent", TEXT_ON_ACCENT),
    ("text-inverse", TEXT_INVERSE),
    ("link", LINK),
    ("link-hover", LINK_HOVER),
    ("border", BORDER),
    ("border-strong", BORDER_STRONG),
    ("border-input", BORDER_INPUT),
    ("border-navy", BORDER_NAVY),
    ("accent", ACCENT),
    ("accent-soft", ACCENT_SOFT),
    ("accent-text", ACCENT_TEXT),
    ("primary", PRIMARY),
    ("primary-hover", PRIMARY_HOVER),
    ("primary-active", PRIMARY_ACTIVE),
    ("toggle-off", TOGGLE_OFF),
    ("toggle-off-hover", TOGGLE_OFF_HOVER),
    ("toggle-off-press", TOGGLE_OFF_PRESS),
    ("toggle-on", TOGGLE_ON),
    ("toggle-on-hover", TOGGLE_ON_HOVER),
    ("toggle-on-press", TOGGLE_ON_PRESS),
    ("unread", UNREAD),
    ("ring-track-selected", RING_TRACK_SELECTED),
    ("nav-active-bg", NAV_ACTIVE_BG),
    ("nav-active-border", NAV_ACTIVE_BORDER),
    ("nav-active-fg", NAV_ACTIVE_FG),
    ("nav-active-icon", NAV_ACTIVE_ICON),
    ("count-soft-bg", COUNT_SOFT_BG),
    ("count-soft-fg", COUNT_SOFT_FG),
    ("count-soft-hover", COUNT_SOFT_HOVER),
    ("icon-accent", ICON_ACCENT),
    ("active-surface", ACTIVE_SURFACE),
    ("active-edge", ACTIVE_EDGE),
    ("active-text", ACTIVE_TEXT),
    ("active-hover", ACTIVE_HOVER),
    ("meter-fill", METER_FILL),
    ("meter-track", METER_TRACK),
    ("meter-warning", METER_WARNING),
    ("pressed", PRESSED),
    ("focus", FOCUS),
    ("caret", CARET),
    ("success", SUCCESS),
    ("success-strong", SUCCESS_STRONG),
    ("success-soft", SUCCESS_SOFT),
    ("warning", WARNING),
    ("warning-strong", WARNING_STRONG),
    ("warning-soft", WARNING_SOFT),
    ("danger", DANGER),
    ("danger-strong", DANGER_STRONG),
    ("danger-soft", DANGER_SOFT),
    ("danger-hover", DANGER_HOVER),
    ("danger-active", DANGER_ACTIVE),
    ("info", INFO),
    ("info-strong", INFO_STRONG),
    ("info-soft", INFO_SOFT),
    ("score-ring-0", SCORE_RING_0),
    ("score-ring-1", SCORE_RING_1),
    ("score-ring-2", SCORE_RING_2),
    ("score-ring-3", SCORE_RING_3),
    ("score-ring-4", SCORE_RING_4),
    ("score-ring-5", SCORE_RING_5),
    ("score-ring-6", SCORE_RING_6),
    ("score-ring-7", SCORE_RING_7),
    ("score-ring-8", SCORE_RING_8),
    ("score-ring-9", SCORE_RING_9),
    ("score-digits", SCORE_DIGITS),
    ("score-high-ring", SCORE_HIGH_RING),
    ("score-high-text", SCORE_HIGH_TEXT),
    ("score-high-surface", SCORE_HIGH_SURFACE),
    ("score-mid-ring", SCORE_MID_RING),
    ("score-mid-text", SCORE_MID_TEXT),
    ("score-mid-surface", SCORE_MID_SURFACE),
    ("score-low-ring", SCORE_LOW_RING),
    ("score-low-text", SCORE_LOW_TEXT),
    ("score-low-surface", SCORE_LOW_SURFACE),
    ("score-track", SCORE_TRACK),
    ("score-excluded", SCORE_EXCLUDED),
    ("score-excluded-track", SCORE_EXCLUDED_TRACK),
    ("brand", BRAND),
    ("brand-glyph", BRAND_GLYPH),
    ("border-focus", BORDER_FOCUS),
    ("control-hover", CONTROL_HOVER),
    ("control-hover-edge", CONTROL_HOVER_EDGE),
    ("raised-hover-edge", RAISED_HOVER_EDGE),
    ("raised-press", RAISED_PRESS),
    ("label-hover", LABEL_HOVER),
    ("label-press", LABEL_PRESS),
    ("label-glyph-hover", LABEL_GLYPH_HOVER),
    ("grip-rest", GRIP_REST),
    ("grip-drag", GRIP_DRAG),
];

// The window's colours in the other palettes (`:root[data-palette='…']`): `--bg`, `--text`
// and `--text-subtle`, which the window and the Windows title bar wear (Coast's are above).
/// `--bg` of light (`--p-cream`).
pub const LIGHT_BG: Colour = Colour::new("hsl(210 28.6% 97.3%)", [0xF6, 0xF8, 0xFA]);
/// `--text` of light (`--p-ink`).
pub const LIGHT_TEXT: Colour = Colour::new("hsl(213 13% 14%)", [0x1F, 0x23, 0x28]);
/// `--text-subtle` of light (`--p-fg-subtle`).
pub const LIGHT_TEXT_SUBTLE: Colour = Colour::new("hsl(212 8% 43%)", [0x65, 0x6D, 0x76]);
/// `--bg` of dark (`--p-cream`).
pub const DARK_BG: Colour = Colour::new("hsl(218 80% 2%)", [0x01, 0x04, 0x09]);
/// `--text` of dark (`--p-ink`).
pub const DARK_TEXT: Colour = Colour::new("hsl(210 66.7% 96.5%)", [0xF0, 0xF6, 0xFC]);
/// `--text-subtle` of dark (`--p-fg-subtle`).
pub const DARK_TEXT_SUBTLE: Colour = Colour::new("hsl(214 8% 55%)", [0x83, 0x8B, 0x95]);

/// The constants above by palette and token.
pub const WINDOW_PALETTES: [(&str, &str, Colour); 6] = [
    ("light", "bg", LIGHT_BG),
    ("light", "text", LIGHT_TEXT),
    ("light", "text-subtle", LIGHT_TEXT_SUBTLE),
    ("dark", "bg", DARK_BG),
    ("dark", "text", DARK_TEXT),
    ("dark", "text-subtle", DARK_TEXT_SUBTLE),
];
