//! Words around a term of an ad and the words that name the profile field it belongs to
//! (`matching::terms`: "Häufig verlangt" in the Profil, the reader's "+").
//!
//! external contract - do not translate: German and English wording of job ads. Every entry
//! is folded like `atoms::fold` (lower case, `ä` -> `a`, `ö` -> `o`, `ü` -> `u`, `ß` -> `ss`),
//! a phrase is words separated by single spaces, each word without the punctuation around
//! it (`o. ä.` is `o a`). Tables searched with `binary_search` are sorted (a test checks).

/// Phrases that open a term and only say that or how it is known (`Kenntnisse in`, `Erfahrung
/// mit`, `experience with`); stripped from the front, the longest first, again and again.
pub(crate) const LEADS: &[&str] = &[
    // German knowledge nouns.
    "anwenderkenntnisse",
    "anwendungskenntnisse",
    "arbeitserfahrung",
    "berufserfahrung",
    "detailkenntnisse",
    "erfahrung",
    "erfahrungen",
    "expertise",
    "fachkenntnisse",
    "fachwissen",
    "fahigkeiten",
    "grundkenntnisse",
    "grundlagen",
    "hintergrund",
    "kenntnis",
    "kenntnisse",
    "kenntnissen",
    "know how",
    "know-how",
    "knowhow",
    "kompetenz",
    "kompetenzen",
    "praxis",
    "praxiserfahrung",
    "praxiskenntnisse",
    "projekterfahrung",
    "qualifikation",
    "routine",
    "sicherer umgang",
    "umgang",
    "verstandnis",
    "vorkenntnisse",
    "wissen",
    // German prepositions, articles and phrases before the term.
    "als",
    "auf",
    "auf dem gebiet",
    "aus",
    "bei",
    "beim",
    "bezuglich",
    "das",
    "dem",
    "den",
    "der",
    "des",
    "die",
    "ein",
    "eine",
    "einem",
    "einer",
    "eines",
    "fur",
    "hinsichtlich",
    "im",
    "im bereich",
    "im umfeld",
    "im umgang mit",
    "in",
    "in bezug auf",
    "in den bereichen",
    "in der anwendung von",
    "mit",
    "rund um",
    "uber",
    "von",
    "vom",
    "zu",
    "zum",
    "zur",
    // German words of weight and number.
    "bspw",
    "ca",
    "circa",
    "einige",
    "ggf",
    "gegebenenfalls",
    "idealerweise",
    "insbesondere",
    "jahr",
    "jahre",
    "jahren",
    "mehrere",
    "min",
    "mind",
    "mindestens",
    "moglichst",
    "sehr",
    "unbedingt",
    "vor allem",
    "vorzugsweise",
    "wunschenswert",
    "zwingend",
    // English articles, prepositions and phrases with them.
    "a",
    "ability to use",
    "across",
    "an",
    "as",
    "at",
    "at least",
    "bonus",
    "experienced in",
    "experienced with",
    "familiar with",
    "for",
    "ideally",
    "including",
    "minimum",
    "must have",
    "must-have",
    "nice to have",
    "nice-to-have",
    "of",
    "on",
    "optional",
    "plus",
    "preferably",
    "proficient in",
    "several",
    "skilled in",
    "some",
    "the",
    "to",
    "using",
    "versed in",
    "well-versed in",
    "with",
    "within",
    "working with",
    "year",
    "years",
    "yrs",
];

/// German qualifiers stripped from the front with or without a declined ending
/// (`fundiert`, `fundierte`, `fundiertes`): `Fundierte SAP-Kenntnisse`, `Verhandlungssicheres
/// Deutsch`, `Abgeschlossenes Studium`.
pub(crate) const GERMAN_QUALIFIERS: &[&str] = &[
    "abgeschlossen",
    "absolviert",
    "ausgepragt",
    "ausgezeichnet",
    "belastbar",
    "breit",
    "einschlagig",
    "entsprechend",
    "erfahren",
    "erst",
    "exzellent",
    "fliessend",
    "fortgeschritten",
    "fundiert",
    "grundlegend",
    "gut",
    "hervorragend",
    "hoh",
    "langjahrig",
    "mehrjahrig",
    "nachgewiesen",
    "nachweisbar",
    "nachweislich",
    "praktisch",
    "profund",
    "relevant",
    "sicher",
    "solid",
    "tief",
    "tiefgehend",
    "tiefgreifend",
    "umfangreich",
    "umfassend",
    "verhandlungssicher",
    "vergleichbar",
    "vertieft",
    "weitreichend",
];

/// Endings of a German qualifier.
pub(crate) const QUALIFIER_ENDINGS: &[&str] = &["", "e", "em", "en", "er", "es"];

/// English qualifiers: stripped only when a lead follows them (`Strong experience in`,
/// `Working knowledge of`), since they also start terms (`Working Capital`, `Deep
/// Learning`, `Advanced Analytics`).
pub(crate) const ENGLISH_QUALIFIERS: &[&str] = &[
    "advanced",
    "basic",
    "broad",
    "comprehensive",
    "considerable",
    "deep",
    "demonstrable",
    "demonstrated",
    "detailed",
    "excellent",
    "extensive",
    "first",
    "good",
    "hands on",
    "hands-on",
    "in-depth",
    "outstanding",
    "practical",
    "previous",
    "prior",
    "professional",
    "profound",
    "proven",
    "relevant",
    "significant",
    "solid",
    "sound",
    "strong",
    "substantial",
    "thorough",
    "very",
    "working",
];

/// English nouns that open a term only before a link word (`Knowledge of IFRS`, `Experience
/// in M&A`); `Knowledge Management` and `Experience Design` are terms of their own.
pub(crate) const ENGLISH_NOUNS: &[&str] = &[
    "background",
    "experience",
    "experiences",
    "expertise",
    "exposure",
    "familiarity",
    "knowledge",
    "proficiency",
    "skill",
    "skills",
    "track record",
    "understanding",
];

/// Link words after an English noun of [`ENGLISH_NOUNS`].
pub(crate) const ENGLISH_LINKS: &[&str] = &[
    "across",
    "around",
    "as",
    "at",
    "for",
    "from",
    "in",
    "including",
    "into",
    "of",
    "on",
    "to",
    "using",
    "with",
    "within",
];

/// English nouns that close a term (`SAP experience`, `Excel skills`) unless the word before
/// them makes a term with them (`Customer Experience`, `Domain Knowledge`, [`ENGLISH_KEPT`]).
pub(crate) const ENGLISH_TAIL_NOUNS: &[&str] = &[
    "background",
    "experience",
    "expertise",
    "knowledge",
    "skills",
];

/// Words that make a term with an English noun after them.
pub(crate) const ENGLISH_KEPT: &[&str] = &[
    "business",
    "candidate",
    "communication",
    "customer",
    "digital",
    "domain",
    "employee",
    "functional",
    "hard",
    "leadership",
    "management",
    "market",
    "patient",
    "people",
    "process",
    "product",
    "professional",
    "project",
    "soft",
    "technical",
    "user",
    "work",
];

/// Knowledge of an industry: the term after (or before) it is an industry
/// (`Branchenerfahrung Energie`, `Energy industry experience`).
pub(crate) const INDUSTRY_NOUNS: &[&str] = &[
    "branchen-know-how",
    "branchenerfahrung",
    "branchenexpertise",
    "branchenhintergrund",
    "branchenkenntnis",
    "branchenkenntnisse",
    "branchenwissen",
    "industrieerfahrung",
    "industry background",
    "industry experience",
    "industry expertise",
    "industry knowledge",
    "sector experience",
    "sector knowledge",
];

/// A last word that says the words before it are an industry (`Pharma Branche`, `chemische
/// Industrie`, `energy sector`); it goes when the words before it are an industry word.
pub(crate) const INDUSTRY_TAILS: &[&str] = &[
    "branche",
    "branchen",
    "industrie",
    "industry",
    "sector",
    "sektor",
];

/// Endings of one word that name an industry whatever comes before them (`Energiebranche`,
/// `Pharmaindustrie`, `IT-Branche`).
pub(crate) const INDUSTRY_ENDINGS: &[&str] = &["branche", "industrie", "sektor"];

/// Endings that name an industry only after an industry word (`Energiewirtschaft`,
/// `Bankenumfeld`; a `Betriebswirtschaft` is none).
pub(crate) const INDUSTRY_WORD_ENDINGS: &[&str] = &[
    "branche",
    "industrie",
    "markt",
    "sektor",
    "umfeld",
    "wirtschaft",
];

/// Endings of an industry compound that go (`Energiebranche` -> `Energie`); an
/// `Automobilindustrie` or an `Energiewirtschaft` keeps its name.
pub(crate) const INDUSTRY_ENDINGS_DROPPED: &[&str] = &["branche", "sektor", "umfeld"];

/// Phrases that close a term and only say how much it is wanted (`von Vorteil`, `setzen wir
/// voraus`, `helfen dabei`, `is a plus`), on top of the engine's nice and mandatory words;
/// stripped from the end, the longest first, again and again.
pub(crate) const TAILS: &[&str] = &[
    "a must",
    "anwenderkenntnisse",
    "are an advantage",
    "are preferred",
    "are required",
    "beneficial",
    "bringen sie mit",
    "bringst du idealerweise mit",
    "bringst du mit",
    "desirable",
    "ein muss",
    "erfahrung",
    "erfahrungen",
    "erforderlich",
    "erwunscht",
    "essential",
    "etc",
    "gewunscht",
    "grundkenntnisse",
    "helfen",
    "helfen dabei",
    "hilft",
    "hilft dabei",
    "hintergrund",
    "in wort & schrift",
    "in wort und schrift",
    "in word and writing",
    "is a must",
    "is an advantage",
    "is beneficial",
    "is desirable",
    "is essential",
    "is preferred",
    "is required",
    "ist erforderlich",
    "ist erwunscht",
    "ist ein muss",
    "ist ein plus",
    "ist notwendig",
    "ist von vorteil",
    "ist wunschenswert",
    "kenntnis",
    "kenntnisse",
    "know how",
    "know-how",
    "knowhow",
    "mitbringen",
    "must",
    "notwendig",
    "o a",
    "o.a",
    "oa",
    "oder ahnlich",
    "oder ahnliches",
    "oder vergleichbar",
    "oder vergleichbare",
    "or comparable",
    "or equivalent",
    "or similar",
    "required",
    "rundet dein profil ab",
    "rundet ihr profil ab",
    "runden dein profil ab",
    "runden ihr profil ab",
    "setzen wir voraus",
    "setzen wir zwingend voraus",
    "sind ein muss",
    "sind ein plus",
    "sind erforderlich",
    "sind erwunscht",
    "sind notwendig",
    "sind von vorteil",
    "sind wunschenswert",
    "spoken and written",
    "usw",
    "vorausgesetzt",
    "vorhanden",
    "ware ein plus",
    "ware von vorteil",
    "waren von vorteil",
    "wird vorausgesetzt",
    "werden vorausgesetzt",
    "wissen",
    "would be a plus",
    "written and spoken",
    "zwingend erforderlich",
];

/// Words of a language requirement around the language (`Englisch fließend`, `Business
/// English` and the like), on top of the engine's level words.
pub(crate) const LANGUAGE_WORDS: &[&str] = &[
    "business",
    "muttersprachler",
    "muttersprachlerin",
    "native speaker",
    "niveau",
    "sprache",
    "sprachkenntnisse",
];

/// Phrases before a certificate (`Zertifizierung als Scrum Master`, `Zulassung als
/// Steuerberater`, `certified`).
pub(crate) const CERTIFICATE_LEADS: &[&str] = &[
    "approbation als",
    "bestellung als",
    "certification",
    "certification as",
    "certification in",
    "certified",
    "zertifikat",
    "zertifikat als",
    "zertifiziert",
    "zertifiziert als",
    "zertifizierte",
    "zertifizierter",
    "zertifizierung",
    "zertifizierung als",
    "zertifizierung in",
    "zertifizierung zum",
    "zertifizierung zur",
    "zulassung als",
    "zulassung zum",
    "zulassung zur",
];

/// Words after a certificate (`PRINCE2 Zertifizierung`, `PMP certification`).
pub(crate) const CERTIFICATE_TAILS: &[&str] = &[
    "certificate",
    "certification",
    "certified",
    "zertifikat",
    "zertifiziert",
    "zertifizierung",
];

/// Endings of one word that make it a certificate (`PMP-Zertifizierung`).
pub(crate) const CERTIFICATE_SUFFIXES: &[&str] = &[
    "-certificate",
    "-certification",
    "-certified",
    "-zertifikat",
    "-zertifiziert",
    "-zertifizierung",
];

/// Certificates by their whole name (keys: words of letters and digits, sorted).
pub(crate) const CERTIFICATES: &[&str] = &[
    "acca",
    "black belt",
    "capm",
    "ccna",
    "ccnp",
    "cfa",
    "cia",
    "cima",
    "cisa",
    "cism",
    "cissp",
    "cpa",
    "cscp",
    "csm",
    "cspo",
    "green belt",
    "ipma level b",
    "ipma level c",
    "ipma level d",
    "itil foundation",
    "itil v4 foundation",
    "lean six sigma black belt",
    "lean six sigma green belt",
    "pmi acp",
    "pmp",
    "prince2 foundation",
    "prince2 practitioner",
    "psm",
    "psm i",
    "psm ii",
    "safe agilist",
    "six sigma black belt",
    "six sigma green belt",
];

/// Codes of a standard: a certification of one is the company's, no certificate of a person
/// (`ISO 9001 Zertifizierung` is a competence).
pub(crate) const STANDARD_CODES: &[&str] = &["din", "iec", "iso"];

/// Degree words of a first word (`Master in Finance`, `Studium der BWL`, `Diplom-Kaufmann`).
pub(crate) const DEGREE_FIRST: &[&str] = &[
    "bachelor",
    "bsc",
    "b.sc",
    "diplom",
    "doktor",
    "doctorate",
    "magister",
    "master",
    "mba",
    "msc",
    "m.sc",
    "phd",
    "ph.d",
    "promotion",
    "staatsexamen",
    "studium",
];

/// Degree words anywhere in a term.
pub(crate) const DEGREE_ANY: &[&str] = &[
    "bachelorabschluss",
    "berufsausbildung",
    "diplomabschluss",
    "fachhochschulabschluss",
    "fachhochschulstudium",
    "hochschulabschluss",
    "hochschulstudium",
    "masterabschluss",
    "mba",
    "phd",
    "studienabschluss",
    "universitatsabschluss",
    "universitatsstudium",
];

/// Endings of a first or last word that make a degree (`BWL-Studium`, `kaufmännische
/// Ausbildung`, `Bankausbildung`).
pub(crate) const DEGREE_ENDINGS: &[&str] = &["ausbildung", "studium"];

/// Words after `Ausbildung` that make it the training of others (`Ausbildung von
/// Mitarbeitern`), no degree.
pub(crate) const TRAINING_OTHERS: &[&str] = &["der", "des", "junger", "neuer", "von"];

/// A degree without a subject says nothing the profile could take (`Hochschulabschluss`).
pub(crate) const GENERIC_DEGREES: &[&str] = &[
    "abschluss",
    "ausbildung",
    "berufsausbildung",
    "degree",
    "fachhochschulabschluss",
    "fachhochschulstudium",
    "hochschulabschluss",
    "hochschulstudium",
    "studienabschluss",
    "studium",
    "universitatsabschluss",
    "universitatsstudium",
    "university degree",
];

/// Tools and methods by their whole name (keys: words of letters, digits, `+` and `#`,
/// sorted): what the profile keeps under `methoden_tools`.
pub(crate) const TOOLS: &[&str] = &[
    "abacus",
    "abap",
    "adobe analytics",
    "agile methoden",
    "agilen methoden",
    "airflow",
    "alteryx",
    "anaplan",
    "angular",
    "ansible",
    "archimate",
    "ariba",
    "aris",
    "asana",
    "autocad",
    "aws",
    "azure",
    "azure devops",
    "bapi",
    "bitbucket",
    "blue prism",
    "board",
    "bpmn",
    "business central",
    "c#",
    "c++",
    "catia",
    "celonis",
    "ci cd",
    "citrix",
    "cobit",
    "cobol",
    "cognos",
    "confluence",
    "corporate planner",
    "coupa",
    "d365",
    "databricks",
    "datev",
    "dbt",
    "design thinking",
    "devops",
    "diamant",
    "docker",
    "doors",
    "dynamics",
    "dynamics 365",
    "dynamics ax",
    "dynamics nav",
    "elasticsearch",
    "enovia",
    "erp",
    "excel",
    "fiori",
    "fmea",
    "gcp",
    "git",
    "github",
    "gitlab",
    "google analytics",
    "google cloud",
    "grafana",
    "hana",
    "hermes",
    "hfm",
    "hubspot",
    "hyperion",
    "idl",
    "idoc",
    "intune",
    "ipma",
    "itil",
    "java",
    "javascript",
    "jedox",
    "jenkins",
    "jira",
    "kafka",
    "kaizen",
    "kanban",
    "kubernetes",
    "labview",
    "lean",
    "lean management",
    "lean six sigma",
    "less",
    "lexware",
    "linux",
    "lodas",
    "loga",
    "lsmw",
    "lucanet",
    "m365",
    "matlab",
    "microsoft 365",
    "microsoft dynamics",
    "microsoft project",
    "miro",
    "mongodb",
    "ms access",
    "ms excel",
    "ms office",
    "ms project",
    "ms visio",
    "mysql",
    "navision",
    "node js",
    "office 365",
    "okr",
    "okrs",
    "onestream",
    "oracle",
    "oracle hyperion",
    "paisy",
    "pdca",
    "personio",
    "php",
    "pl sql",
    "planning analytics",
    "pmbok",
    "polarion",
    "postgresql",
    "postman",
    "power apps",
    "power automate",
    "power bi",
    "power pivot",
    "power query",
    "powerbi",
    "powerpoint",
    "primavera",
    "prince2",
    "proalpha",
    "python",
    "qlik",
    "qlik sense",
    "qlikview",
    "r",
    "react",
    "rpa",
    "s 4hana",
    "s4hana",
    "safe",
    "sage",
    "salesforce",
    "sas",
    "scrum",
    "servicenow",
    "sharepoint",
    "signavio",
    "simulink",
    "six sigma",
    "snowflake",
    "solidworks",
    "spark",
    "splunk",
    "spss",
    "sql",
    "ssis",
    "ssrs",
    "stata",
    "successfactors",
    "swagger",
    "t sql",
    "tableau",
    "tagetik",
    "teamcenter",
    "terraform",
    "tm1",
    "togaf",
    "tosca",
    "trackwise",
    "trello",
    "typescript",
    "uipath",
    "uml",
    "unix",
    "v modell",
    "vba",
    "veeva",
    "visio",
    "vmware",
    "wasserfall",
    "windchill",
    "workday",
    "zendesk",
];

/// First words of a family of tools (`SAP Analytics Cloud`, `MS Project`, `IBM Cognos`,
/// sorted); a module code after a hyphen belongs to it (`SAP-FI`).
pub(crate) const TOOL_FAMILIES: &[&str] = &[
    "adobe",
    "atlassian",
    "aws",
    "azure",
    "celonis",
    "datev",
    "dynamics",
    "google",
    "ibm",
    "infor",
    "jira",
    "microsoft",
    "ms",
    "oracle",
    "qlik",
    "sage",
    "salesforce",
    "sap",
    "servicenow",
    "tableau",
    "veeva",
    "workday",
];

/// Most letters of a module code after a tool family and a hyphen (`SAP-FI`, `SAP-HCM`).
pub(crate) const MODULE_CODE_CHARS: usize = 4;
