// Mirrors the colours of ui/src/styles/tokens.css into everything that is not the page, so
// tokens.css stays the one place a colour is written (docs/CHANGING.md, "Change the look"):
//
//   core/src/export/palette.rs   every colour token as a Rust constant: the report, the Excel
//                                file and the Windows title bar (src-tauri/src/platform.rs)
//   tools/palette.json           the same for tools/icon.py (the app icon)
//   src-tauri/tauri*.conf.json   the window's backgroundColor (--bg: no flash before the page
//                                paints, and the cream under the Windows title bar)
//
//     node tools/tokens.mjs           writes the files
//     node tools/tokens.mjs --check   fails when one of them does not say what tokens.css says
//
// `npm run regen` runs it and then tools/icon.py. A colour token is a semantic token whose
// value is `hsl(var(--p-name))` or `var(--other)` of another colour token; tokens with an
// alpha, gradients and shadows stay in the page. core/tests/palette.rs checks the generated
// files against tokens.css on its own (cargo test runs in CI).

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS = 'ui/src/styles/tokens.css';
const RUST = 'core/src/export/palette.rs';
const JSON_OUT = 'tools/palette.json';
const CONFIGS = ['src-tauri/tauri.conf.json', 'src-tauri/tauri.macos.conf.json'];
/** The token the window paints before the page (and the Windows title bar wears). */
const WINDOW = 'bg';
/** The font stack of the report. */
const FONT = 'font-sans';
const GENERATED = `Generated by tools/tokens.mjs from ${TOKENS}, do not edit`;
/** rustfmt's line width. */
const WIDTH = 100;

/* ------------------------------------------------------------------ tokens */

/** The declarations of the first `:root` block, by name without the dashes, in order. */
function declarations(css) {
  const code = css.replace(/\/\*[\s\S]*?\*\//g, '');
  const start = code.indexOf(':root {');
  if (start < 0) throw new Error(`${TOKENS}: no :root block`);
  const body = code.slice(start + ':root {'.length, code.indexOf('}', start));
  const out = new Map();
  for (const part of body.split(';')) {
    const match = /^\s*--([\w-]+)\s*:\s*([\s\S]*?)\s*$/.exec(part);
    if (match) out.set(match[1], match[2].replace(/\s+/g, ' '));
  }
  return out;
}

/** An HSL triplet (`13 73% 63%`) as sRGB bytes, rounded like a browser. */
function rgb(triplet) {
  const [hue, saturation, lightness] = triplet
    .split(' ')
    .map((part, i) => Number.parseFloat(part) / (i === 0 ? 1 : 100));
  const chroma = (1 - Math.abs(2 * lightness - 1)) * saturation;
  const second = chroma * (1 - Math.abs(((hue / 60) % 2) - 1));
  const base = lightness - chroma / 2;
  const sector = [
    [chroma, second, 0],
    [second, chroma, 0],
    [0, chroma, second],
    [0, second, chroma],
    [second, 0, chroma],
    [chroma, 0, second],
  ][Math.min(5, Math.floor(hue / 60))];
  return sector.map((channel) => Math.round((channel + base) * 255));
}

/**
 * The colour tokens in the order of tokens.css: name, the chain of names it resolves through
 * (the last one a palette entry), its CSS and its bytes.
 */
function colours(tokens) {
  const palette = new Map();
  for (const [name, value] of tokens) {
    if (!name.startsWith('p-')) continue;
    if (!/^\d+(\.\d+)? \d+(\.\d+)?% \d+(\.\d+)?%$/.test(value)) {
      throw new Error(`${TOKENS}: --${name} is not an HSL triplet (${value})`);
    }
    palette.set(name, value);
  }
  const resolve = (name, chain) => {
    const value = tokens.get(name);
    const direct = /^hsl\(var\(--(p-[\w-]+)\)\)$/.exec(value);
    if (direct) {
      if (!palette.has(direct[1])) throw new Error(`${TOKENS}: --${name} names no palette entry`);
      return { chain: [...chain, direct[1]], triplet: palette.get(direct[1]) };
    }
    const alias = /^var\(--([\w-]+)\)$/.exec(value);
    if (alias && tokens.has(alias[1]) && !alias[1].startsWith('p-')) {
      return resolve(alias[1], [...chain, alias[1]]);
    }
    return null;
  };
  const out = [];
  for (const name of tokens.keys()) {
    if (name.startsWith('p-')) continue;
    const found = resolve(name, []);
    if (found === null) continue;
    out.push({
      name,
      chain: found.chain,
      css: `hsl(${found.triplet})`,
      rgb: rgb(found.triplet),
    });
  }
  return out;
}

/** `score-ring-0` ... `score-ring-9` as one family `score-ring` of ten. */
function families(list) {
  const groups = new Map();
  for (const { name } of list) {
    const match = /^(.+)-(\d+)$/.exec(name);
    if (!match) continue;
    groups.set(match[1], [...(groups.get(match[1]) ?? []), Number(match[2])]);
  }
  const names = new Set(list.map((c) => c.name));
  return [...groups]
    .filter(([, steps]) => steps.every((step, i) => step === i))
    .map(([base, steps]) => {
      if (names.has(base)) throw new Error(`${TOKENS}: --${base} and --${base}-0 ... collide`);
      return { base, size: steps.length };
    });
}

/* -------------------------------------------------------------------- Rust */

const constant = (name) => name.toUpperCase().replaceAll('-', '_');
const byte = (b) => b.toString(16).toUpperCase().padStart(2, '0');

/** `pub const NAME: Type = value;`, broken after `=` where rustfmt breaks it. */
function item(head, value) {
  const line = `${head} = ${value};`;
  return line.length <= WIDTH ? line : `${head} =\n    ${value};`;
}

/** An array literal as rustfmt writes it: one line when it fits, else one entry a line. */
function array(head, entries) {
  const line = `${head} = [${entries.join(', ')}];`;
  if (line.length <= WIDTH && entries.join(', ').length <= 60) return line;
  return `${head} = [\n${entries.map((e) => `    ${e},\n`).join('')}];`;
}

function rust(list, font) {
  const byName = new Map(list.map((c) => [c.name, c]));
  const out = [
    `//! ${GENERATED}: change`,
    '//! tokens.css and run `npm run regen` (docs/CHANGING.md, "Change the look").',
    '//!',
    '//! The colours of the app for everything that is not the page: the report, the Excel file',
    '//! and the Windows title bar (src-tauri). Each constant is a colour token of tokens.css,',
    '//! resolved to its palette entry (the doc comment names the chain); `core/tests/palette.rs`',
    '//! fails when this file no longer says what tokens.css says.',
    '',
    'pub use super::colour::Colour;',
    '',
  ];
  for (const c of list) {
    const via = c.chain.map((n) => `\`--${n}\``).join(', ');
    out.push(`/// \`--${c.name}\` (${via}).`);
    const target = byName.get(c.chain[0]);
    const value =
      target === undefined
        ? `Colour::new("${c.css}", [${c.rgb.map((b) => `0x${byte(b)}`).join(', ')}])`
        : constant(target.name);
    out.push(item(`pub const ${constant(c.name)}: Colour`, value));
  }
  for (const { base, size } of families(list)) {
    const steps = Array.from({ length: size }, (_, i) => constant(`${base}-${i}`));
    out.push('', `/// \`--${base}-0\` ... \`--${base}-${size - 1}\` in order.`);
    out.push(array(`pub const ${constant(base)}: [Colour; ${size}]`, steps));
  }
  out.push('', `/// \`--${FONT}\`.`, item('pub const FONT_SANS: &str', JSON.stringify(font)));
  out.push('', '/// Every colour constant above by the name of its token (without the dashes).');
  out.push(
    array(
      `pub const TOKENS: [(&str, Colour); ${list.length}]`,
      list.map((c) => `("${c.name}", ${constant(c.name)})`),
    ),
  );
  return `${out.join('\n')}\n`;
}

/* -------------------------------------------------------------------- JSON */

function json(list, font) {
  const width = Math.max(...list.map((c) => c.name.length));
  const rows = list.map((c, i) => {
    const key = `"${c.name}":`.padEnd(width + 3);
    const comma = i < list.length - 1 ? ',' : '';
    return `    ${key} { "css": "${c.css}", "rgb": [${c.rgb.join(', ')}] }${comma}`;
  });
  return [
    '{',
    `  "note": "${GENERATED}.",`,
    '  "colours": {',
    ...rows,
    '  },',
    `  "fontSans": ${JSON.stringify(font)}`,
    '}',
    '',
  ].join('\n');
}

/* ------------------------------------------------------------------ window */

/** The configuration with its window's backgroundColor set (the rest of the text kept). */
function config(text, file, bytes) {
  const pattern = /("backgroundColor":\s*")#[0-9A-Fa-f]{6}(")/;
  if (!pattern.test(text)) throw new Error(`${file}: no backgroundColor`);
  return text.replace(pattern, `$1#${bytes.map(byte).join('')}$2`);
}

/* -------------------------------------------------------------------- main */

const read = (file) => readFileSync(join(repo, file), 'utf8');
const tokens = declarations(read(TOKENS));
const list = colours(tokens);
const font = tokens.get(FONT);
const background = list.find((c) => c.name === WINDOW);
if (font === undefined || background === undefined) {
  throw new Error(`${TOKENS}: --${FONT} or --${WINDOW} missing`);
}
const files = new Map([
  [RUST, rust(list, font)],
  [JSON_OUT, json(list, font)],
  ...CONFIGS.map((file) => [file, config(read(file), file, background.rgb)]),
]);

if (process.argv.includes('--check')) {
  const stale = [...files].filter(([file, text]) => read(file) !== text).map(([file]) => file);
  if (stale.length > 0) {
    console.error(`Stale against ${TOKENS} (run npm run regen):\n  ${stale.join('\n  ')}`);
    process.exit(1);
  }
} else {
  for (const [file, text] of files) writeFileSync(join(repo, file), text);
  console.log(`${list.length} colour tokens written to ${[...files.keys()].join(', ')}`);
}
