// Mirrors the colours of ui/src/styles/tokens.css into everything that is not the page, so
// tokens.css stays the one place a colour is written (docs/CHANGING.md, "Change the look"):
//
//   core/src/export/palette.rs   the colour tokens of CXact (the `:root` block) that something
//                                besides the page wears (`OUTSIDE`) as Rust constants: the
//                                Excel file, the window (src-tauri/src/platform.rs) and the
//                                icon's tests; and the window's colour (--bg) of every other
//                                palette
//   tools/palette.json           CXact's colour tokens for tools/icon.py (the app icon)
//   src-tauri/tauri*.conf.json   the window's backgroundColor (CXact's --bg: no flash before
//                                the page paints)
//
//     node tools/tokens.mjs           writes the files
//     node tools/tokens.mjs --check   fails when one of them does not say what tokens.css says
//
// Both also measure every text role on the backgrounds it stands on, in every palette
// (`CONTRAST`, WCAG AA), and fail below it. `npm run regen` runs it and then tools/icon.py.
// A colour token is a semantic token whose value is `hsl(var(--p-name))` or `var(--other)` of
// another colour token; tokens with an alpha, gradients and shadows stay in the page.
// core/tests/palette.rs checks the generated files against tokens.css on its own (cargo test
// runs in CI).

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS = 'ui/src/styles/tokens.css';
const RUST = 'core/src/export/palette.rs';
const JSON_OUT = 'tools/palette.json';
const CONFIGS = ['src-tauri/tauri.conf.json', 'src-tauri/tauri.macos.conf.json'];
/** The token the window paints before the page. */
const WINDOW = 'bg';
/** What the window wears in every palette: its background (src-tauri/src/platform.rs; the top
 *  bar is the page's own, --titlebar-*). */
const WINDOW_TOKENS = ['bg'];
/** The palette of the `:root` block (the default; `Palette::Cxact` in core/src/settings.rs). */
const BASE_PALETTE = 'cxact';
/**
 * The colour tokens something besides the page wears, the only ones palette.rs holds: the
 * window (bg), the Excel file (the header row's
 * surface-muted, the excluded rows' score-excluded, the score cells' score-ring-0 ... 9) and
 * the app icon (brand, brand-glyph; core/tests/icon.rs). A family is named by its base.
 */
const OUTSIDE = ['bg', 'surface-muted', 'score-excluded', 'score-ring', 'brand', 'brand-glyph'];
const GENERATED = `Generated by tools/tokens.mjs from ${TOKENS}, do not edit`;
/** rustfmt's line width. */
const WIDTH = 100;

/**
 * The text roles and the backgrounds each one stands on, as the components use them. A
 * background `a/b` is `a` (a wash with an alpha) laid over `b`; a text with an alpha is laid
 * over its background. Every pair keeps WCAG AA for body text (4.5:1) in every palette.
 */
const CONTRAST = [
  {
    text: ['text', 'text-muted', 'text-subtle', 'text-heading', 'text-label', 'link'],
    on: ['bg', 'surface', 'surface-muted', 'surface-selected', 'surface-hover/surface'],
  },
  {
    text: ['text'],
    on: [
      'surface-selected-hover',
      'surface-selected-press',
      'surface-selected-inactive/surface',
      'surface-press/surface',
      'active-surface',
      'nav-active-bg',
    ],
  },
  { text: ['accent-text'], on: ['surface', 'accent-soft'] },
  {
    text: ['text-on-accent'],
    on: ['primary', 'primary-hover', 'primary-active'],
  },
  { text: ['text-on-danger'], on: ['danger-strong', 'danger-hover'] },
  { text: ['text-inverse', 'text-inverse-muted'], on: ['surface-inverse'] },
  { text: ['count-soft-fg'], on: ['count-soft-bg', 'count-soft-hover'] },
  { text: ['nav-active-fg'], on: ['nav-active-bg'] },
  { text: ['active-text'], on: ['active-surface', 'active-hover'] },
  { text: ['success-strong'], on: ['surface', 'success-soft'] },
  { text: ['warning-strong'], on: ['surface', 'warning-soft'] },
  { text: ['danger-strong'], on: ['surface', 'danger-soft'] },
  { text: ['info', 'info-strong'], on: ['surface', 'info-soft'] },
  { text: ['score-high-text'], on: ['surface', 'score-high-surface'] },
  { text: ['score-mid-text'], on: ['surface', 'score-mid-surface'] },
  { text: ['score-low-text'], on: ['surface', 'score-low-surface'] },
  { text: ['score-digits'], on: ['surface', 'surface-selected'] },
];
/** WCAG AA for body text. */
const AA = 4.5;
/** Pairs below AA by a documented decision of the user (docs/PLAN.md): the CXact coral of the
 *  primary with its white label (3.7:1 at rest, 4.4:1 under the pointer; large enough text
 *  for 3:1, and brighter than the old CXact's 2.8:1). */
const EXCEPTIONS = new Set([
  'cxact: --text-on-accent on --primary',
  'cxact: --text-on-accent on --primary-hover',
]);

/* ------------------------------------------------------------------ tokens */

/** The custom properties of a block's body, by name without the dashes, in order. */
function parse(body) {
  const out = new Map();
  for (const part of body.split(';')) {
    const match = /^\s*--([\w-]+)\s*:\s*([\s\S]*?)\s*$/.exec(part);
    if (match) out.set(match[1], match[2].replace(/\s+/g, ' '));
  }
  return out;
}

const withoutComments = (css) => css.replace(/\/\*[\s\S]*?\*\//g, '');

/** The declarations of the first `:root` block (CXact), by name without the dashes, in order. */
function declarations(css) {
  const code = withoutComments(css);
  const start = code.indexOf(':root {');
  if (start < 0) throw new Error(`${TOKENS}: no :root block`);
  return parse(code.slice(start + ':root {'.length, code.indexOf('}', start)));
}

/**
 * Every palette by name, CXact first: its whole set of declarations (CXact's, with the ones
 * of its `:root[data-palette='name']` block laid over them).
 */
function palettes(css) {
  const base = declarations(css);
  const code = withoutComments(css);
  const out = new Map([[BASE_PALETTE, base]]);
  for (const found of code.matchAll(/:root\[data-palette='([\w-]+)'\]\s*\{([^}]*)\}/g)) {
    const [, name, body] = found;
    if (out.has(name)) throw new Error(`${TOKENS}: palette ${name} twice`);
    out.set(name, new Map([...base, ...parse(body)]));
  }
  return out;
}

/** An HSL triplet (`13 73% 63%`) as sRGB bytes, rounded like a browser. */
function rgb(triplet) {
  const [hue, saturation, lightness] = triplet
    .split(' ')
    .map((part, i) => Number.parseFloat(part) / (i === 0 ? 1 : 100));
  const chroma = (1 - Math.abs(2 * lightness - 1)) * saturation;
  const second = chroma * (1 - Math.abs(((hue / 60) % 2) - 1));
  const base = lightness - chroma / 2;
  const sector = [
    [chroma, second, 0],
    [second, chroma, 0],
    [0, chroma, second],
    [0, second, chroma],
    [second, 0, chroma],
    [chroma, 0, second],
  ][Math.min(5, Math.floor(hue / 60))];
  return sector.map((channel) => Math.round((channel + base) * 255));
}

/**
 * The colour tokens in the order of tokens.css: name, the chain of names it resolves through
 * (the last one a palette entry), its CSS and its bytes.
 */
function colours(tokens) {
  const palette = new Map();
  for (const [name, value] of tokens) {
    if (!name.startsWith('p-')) continue;
    if (!/^\d+(\.\d+)? \d+(\.\d+)?% \d+(\.\d+)?%$/.test(value)) {
      throw new Error(`${TOKENS}: --${name} is not an HSL triplet (${value})`);
    }
    palette.set(name, value);
  }
  const resolve = (name, chain) => {
    const value = tokens.get(name);
    const direct = /^hsl\(var\(--(p-[\w-]+)\)\)$/.exec(value);
    if (direct) {
      if (!palette.has(direct[1])) throw new Error(`${TOKENS}: --${name} names no palette entry`);
      return { chain: [...chain, direct[1]], triplet: palette.get(direct[1]) };
    }
    const alias = /^var\(--([\w-]+)\)$/.exec(value);
    if (alias && tokens.has(alias[1]) && !alias[1].startsWith('p-')) {
      return resolve(alias[1], [...chain, alias[1]]);
    }
    return null;
  };
  const out = [];
  for (const name of tokens.keys()) {
    if (name.startsWith('p-')) continue;
    const found = resolve(name, []);
    if (found === null) continue;
    out.push({
      name,
      chain: found.chain,
      css: `hsl(${found.triplet})`,
      rgb: rgb(found.triplet),
    });
  }
  return out;
}

/** `score-ring-0` ... `score-ring-9` as one family `score-ring` of ten. */
function families(list) {
  const groups = new Map();
  for (const { name } of list) {
    const match = /^(.+)-(\d+)$/.exec(name);
    if (!match) continue;
    groups.set(match[1], [...(groups.get(match[1]) ?? []), Number(match[2])]);
  }
  const names = new Set(list.map((c) => c.name));
  return [...groups]
    .filter(([, steps]) => steps.every((step, i) => step === i))
    .map(([base, steps]) => {
      if (names.has(base)) throw new Error(`${TOKENS}: --${base} and --${base}-0 ... collide`);
      return { base, size: steps.length };
    });
}

/* -------------------------------------------------------------------- Rust */

const constant = (name) => name.toUpperCase().replaceAll('-', '_');
const byte = (b) => b.toString(16).toUpperCase().padStart(2, '0');

/** `pub const NAME: Type = value;`, broken after `=` where rustfmt breaks it. */
function item(head, value) {
  const line = `${head} = ${value};`;
  return line.length <= WIDTH ? line : `${head} =\n    ${value};`;
}

/** An array literal as rustfmt writes it: a short one (its `array_width`, 60) on one line,
 *  after the `=` where the head leaves no room for it; else one entry a line. */
function array(head, entries) {
  const inline = entries.join(', ');
  if (inline.length <= 60) return item(head, `[${inline}]`);
  return `${head} = [\n${entries.map((e) => `    ${e},\n`).join('')}];`;
}

/** `Colour::new("hsl(…)", [0x…, …])`. */
const colourLiteral = (c) =>
  `Colour::new("${c.css}", [${c.rgb.map((b) => `0x${byte(b)}`).join(', ')}])`;

/** The window's colours of the palettes besides CXact: one constant per palette and token,
 *  and the table of them by palette and token (what core/tests/palette.rs compares). */
function windowItems(windows) {
  const out = [
    '',
    "// The window's colour in the other palettes (`:root[data-palette='…']`): `--bg`, which the",
    "// window wears before the page paints (CXact's is above).",
  ];
  const table = [];
  for (const [palette, list] of windows) {
    for (const c of list) {
      const name = constant(`${palette}-${c.name}`);
      out.push(`/// \`--${c.name}\` of ${palette} (\`--${c.chain.at(-1)}\`).`);
      out.push(item(`pub const ${name}: Colour`, colourLiteral(c)));
      table.push(`("${palette}", "${c.name}", ${name})`);
    }
  }
  out.push('', '/// The constants above by palette and token.');
  out.push(array(`pub const WINDOW_PALETTES: [(&str, &str, Colour); ${table.length}]`, table));
  return out;
}

/** The entry of `OUTSIDE` a token belongs to: its name, or the base of its family. */
const outsideName = (name) =>
  [name, name.replace(/-\d+$/, '')].find((candidate) => OUTSIDE.includes(candidate));

function rust(all, windows) {
  const list = all.filter((c) => outsideName(c.name) !== undefined);
  const missing = OUTSIDE.filter((name) => !list.some((c) => outsideName(c.name) === name));
  if (missing.length > 0) throw new Error(`${TOKENS}: no colour token --${missing.join(', --')}`);
  const byName = new Map(list.map((c) => [c.name, c]));
  const out = [
    `//! ${GENERATED}: change`,
    '//! tokens.css and run `npm run regen` (docs/CHANGING.md, "Change the look").',
    '//!',
    '//! The colours of the app that something besides the page wears: the Excel file, the',
    '//! window (src-tauri) and the app icon. Each constant is a colour token of tokens.css,',
    '//! resolved to its palette entry (the doc comment names the chain);',
    '//! `core/tests/palette.rs` fails when this file no longer says what tokens.css says.',
    '',
    'pub use super::colour::Colour;',
    '',
  ];
  for (const c of list) {
    const via = c.chain.map((n) => `\`--${n}\``).join(', ');
    out.push(`/// \`--${c.name}\` (${via}).`);
    const target = byName.get(c.chain[0]);
    const value = target === undefined ? colourLiteral(c) : constant(target.name);
    out.push(item(`pub const ${constant(c.name)}: Colour`, value));
  }
  for (const { base, size } of families(list)) {
    const steps = Array.from({ length: size }, (_, i) => constant(`${base}-${i}`));
    out.push('', `/// \`--${base}-0\` ... \`--${base}-${size - 1}\` in order.`);
    out.push(array(`pub const ${constant(base)}: [Colour; ${size}]`, steps));
  }
  out.push('', '/// Every colour constant above by the name of its token (without the dashes).');
  out.push(
    array(
      `pub const TOKENS: [(&str, Colour); ${list.length}]`,
      list.map((c) => `("${c.name}", ${constant(c.name)})`),
    ),
  );
  out.push(...windowItems(windows));
  return `${out.join('\n')}\n`;
}

/* -------------------------------------------------------------------- JSON */

function json(list) {
  const width = Math.max(...list.map((c) => c.name.length));
  const rows = list.map((c, i) => {
    const key = `"${c.name}":`.padEnd(width + 3);
    const comma = i < list.length - 1 ? ',' : '';
    return `    ${key} { "css": "${c.css}", "rgb": [${c.rgb.join(', ')}] }${comma}`;
  });
  return ['{', `  "note": "${GENERATED}.",`, '  "colours": {', ...rows, '  }', '}', ''].join('\n');
}

/* ------------------------------------------------------------------ window */

/** The configuration with its window's backgroundColor set (the rest of the text kept). */
function config(text, file, bytes) {
  const pattern = /("backgroundColor":\s*")#[0-9A-Fa-f]{6}(")/;
  if (!pattern.test(text)) throw new Error(`${file}: no backgroundColor`);
  return text.replace(pattern, `$1#${bytes.map(byte).join('')}$2`);
}

/* ---------------------------------------------------------------- contrast */

/** sRGB bytes to relative luminance (WCAG 2). */
function luminance(bytes) {
  const [r, g, b] = bytes.map((value) => {
    const c = value / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/** `top` with its alpha laid over the opaque `base`. */
const over = (top, base) =>
  top.rgb.map((channel, i) => Math.round(channel * top.alpha + base[i] * (1 - top.alpha)));

/** A colour role of a palette as bytes and alpha: `hsl(var(--p-x))`, `hsl(var(--p-x) / a)` or
 *  `var(--role)`. */
function paint(tokens, name) {
  const value = tokens.get(name);
  if (value === undefined)
    throw new Error(`${TOKENS}: CONTRAST names --${name}, which is no token`);
  const direct = /^hsl\(var\(--(p-[\w-]+)\)(?: \/ ([\d.]+))?\)$/.exec(value);
  if (direct) {
    const triplet = tokens.get(direct[1]);
    if (triplet === undefined) throw new Error(`${TOKENS}: --${name} names no palette entry`);
    return { rgb: rgb(triplet), alpha: direct[2] === undefined ? 1 : Number(direct[2]) };
  }
  const alias = /^var\(--([\w-]+)\)$/.exec(value);
  if (alias) return paint(tokens, alias[1]);
  throw new Error(`${TOKENS}: --${name} is no colour (${value})`);
}

/** Every text of CONTRAST below AA on one of its backgrounds, in every palette. */
function contrastProblems(all) {
  const problems = [];
  for (const [palette, tokens] of all) {
    for (const { text, on } of CONTRAST) {
      for (const background of on) {
        const [top, ...under] = background.split('/');
        let ground = paint(tokens, top);
        for (const name of under) ground = { rgb: over(ground, paint(tokens, name).rgb), alpha: 1 };
        if (ground.alpha < 1) throw new Error(`${TOKENS}: --${top} needs a background under it`);
        for (const name of text) {
          const ink = over(paint(tokens, name), ground.rgb);
          const [light, dark] = [luminance(ink), luminance(ground.rgb)].sort((a, b) => b - a);
          const ratio = (light + 0.05) / (dark + 0.05);
          const pair = `${palette}: --${name} on --${background}`;
          if (ratio < AA && !EXCEPTIONS.has(pair)) problems.push(`${pair} ${ratio.toFixed(2)}:1`);
        }
      }
    }
  }
  return problems;
}

/* -------------------------------------------------------------------- main */

const read = (file) => readFileSync(join(repo, file), 'utf8');
const all = palettes(read(TOKENS));
const tokens = all.get(BASE_PALETTE);
const list = colours(tokens);
const background = list.find((c) => c.name === WINDOW);
if (background === undefined) throw new Error(`${TOKENS}: --${WINDOW} missing`);
/** The window's tokens of every palette besides CXact. */
const windows = [...all]
  .filter(([name]) => name !== BASE_PALETTE)
  .map(([name, merged]) => {
    const found = colours(merged);
    return [name, WINDOW_TOKENS.map((token) => found.find((c) => c.name === token))];
  });
for (const [name, found] of windows) {
  if (found.includes(undefined)) throw new Error(`${TOKENS}: ${name} lacks a window colour`);
}
const files = new Map([
  [RUST, rust(list, windows)],
  [JSON_OUT, json(list)],
  ...CONFIGS.map((file) => [file, config(read(file), file, background.rgb)]),
]);
const weak = contrastProblems(all);

if (process.argv.includes('--check')) {
  const stale = [...files].filter(([file, text]) => read(file) !== text).map(([file]) => file);
  if (stale.length > 0) {
    console.error(`Stale against ${TOKENS} (run npm run regen):\n  ${stale.join('\n  ')}`);
    process.exit(1);
  }
} else {
  for (const [file, text] of files) writeFileSync(join(repo, file), text);
  console.log(`${list.length} colour tokens written to ${[...files.keys()].join(', ')}`);
}
if (weak.length > 0) {
  console.error(`Text below WCAG AA (${AA}:1) in ${TOKENS}:\n  ${weak.join('\n  ')}`);
  process.exit(1);
}
